### ISSUE TITLE
[U2U] Add support for U2U network

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#106]
Please look into the following materials to see if we can integrate the U2U Network. Thank you!

**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team:
Unicorn Ultra (U2U) is the 2nd layer-1 in the world to adopt Hashgraph technology as the distributed ledger system to drive its ecosystem.
- Basic information about your team (as transparent as possible):
See team info on https://uniultra.xyz/ 
- Social media links (telegram, discord, website, LinkedIn,...)
Website: https://uniultra.xyz/ 
Telegram: https://t.me/UnicornUltra
Discord: https://discord.com/invite/QE3J7KVwNp
Linkedin: https://www.linkedin.com/company/unicorn-ultra/
- Whitepaper (if you have one)
https://docs.uniultra.xyz/u2u-whitepaper/
- An email (and element channel if you have one)
- Github

Please tag @RyanDinh8 or @Mabel-Nguyen if you want to discuss business

**If you want to integrate a chain, you would need to provide**
Here are a few resources to help with the research. Note: U2U API & SDK information is still being finalized and they will send it once they are finished!
- Developer Docs: https://docs.uniultra.xyz/u2u-chain-documents/
- U2U Blog: https://uniultra.xyz/blog
- Testnet: https://testnet.u2uscan.xyz

- Dataroom: https://docsend.com/view/giemat5jjpctasaq

- Recent Medium article about their Hashgraph-powered testnet:
https://medium.com/unicorn-ultra/nebulas-testnet-an-ambitious-step-of-the-u2u-chain-before-the-next-bullrun-d99024a12435

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1899-build-1.1.11-1-2023-09-12T08-57-59UTC.zip

Validation passed for case:
- Show balance
- View block explorer
- Transfer balance

Waiting to confirm transfer all
