### ISSUE TITLE
[Ethereum, BSC] [USDD] Add support for USDD on Ethereum, BSC

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#110]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team:
USDD (Decentralized USD) is the first over-collateralized decentralized stablecoin with a guaranteed minimum collateral ratio of 120%. It has been launched collaboratively by the TRON DAO Reserve and top-tier mainstream blockchain institutions.
- Basic information about your team (as transparent as possible)
The TRON DAO Reserve is the custodian of USDD and guarantees its price stability. See https://tdr.org/#/
- Whitepaper (if you have one)
https://usdd.io/USDD-en.pdf
- Social media links (telegram, discord, website, LinkedIn,...)
Website: https://usdd.io/
Twitter: https://twitter.com/usddio
Telegram: https://t.me/tronnetworkEN
Discord: https://discord.com/invite/hqKvyAM
- Any other useful material so we can get to know you better
Docs: https://docs.usdd.io/
- Github
- Any grant information you can provide (W3F Grants, Substrate Builders Program,...) (optional)

Please tag @RyanDinh8 or @Mabel-Nguyen if you want to discuss business

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: USDD
- Origin blockchain of the asset: Tron
- Is it available on other blockchains? Ethereum, BSC
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
Smart contract address on Tron: TPYmHEhy5n8TCEfYGqW2rPxsghSfzghPDn
Smart contract address on Ethereum: 0x0C10bF8FcB7Bf5412187A595ab97a3609160b5c6
Smart contract address on BSC: 0xd17479997F34dd9156Deef8F95A52D81D265be9c
- Logo of the token: https://drive.google.com/drive/folders/1lBAxBfwenkwwRNJyt-QA_gsJGaOwHDHv?usp=sharing
- Is your asset transferable?

**Documents and references:**
Please attach all sources of the information you provided above
https://tronscan.org/#/token20/TPYmHEhy5n8TCEfYGqW2rPxsghSfzghPDn
https://etherscan.io/token/0x0c10bf8fcb7bf5412187a595ab97a3609160b5c6
https://bscscan.com/token/0xd17479997f34dd9156deef8f95a52d81d265be9c

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1884-build-1.1.10-2023-09-06T11-13-43UTC.zip

Validation passed
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/c04bfcaf-7925-4454-aeca-bf23404aa5ad)
