### ISSUE TITLE
[Base] Add support for Base blockchain

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#112]
Please help integrate the Base Mainnet. Let me know if you need further information!

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Base Mainnet
- Type of the blockchain (can be Substrate, EVM or both): EVM
- RPC endpoint: https://mainnet.base.org/
- Chain ID: 8453
- Currency symbol: ETH
- Logo of the blockchain: https://github.com/base-org/brand-kit/tree/main/logo/symbol
- Block explorers (if possible) https://basescan.org/

**Documents and references:**
Please attach all sources of the information you provided above
- Website: https://base.org/
- https://docs.base.org/network-information
- https://github.com/base-org

**Comment by Sokol142196** [comment]
@Mabel-Nguyen please re-check Block explorers of this network.
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/e175ac6d-d1fb-4258-86f6-8a8c0c8413b9)
