### ISSUE TITLE
[Avalanche C] Add support for Avalanche C-CHain

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#113]
Please help add support for Avalanche (C-Chain). Let me know if you need further information! 

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Avalanche (C-Chain)
- Type of the blockchain (can be Substrate, EVM or both): EVM
- Blockchain providers (WS or HTTP). HTTP is preferable for EVM-compatible chains.
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Please see docs at https://docs.avax.network/reference/avalanchego/c-chain/api
- Logo of the blockchain: https://drive.google.com/drive/folders/1zeNCdelQwx0muHCuIn_Z2l-SsCNUw1BD
- Block explorers (if possible): https://subnets.avax.network/c-chain

**Documents and references:**
Please attach all sources of the information you provided above
- Website: https://www.avax.network/
- https://docs.avax.network/learn/avalanche/avalanche-platform#c-chain
- https://support.avax.network/en/articles/4132288-avalanche-press-kit-and-brand-assets

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/cDA6dxdscSdWEfN

Validation passed
