### ISSUE TITLE
Support more DOT tokens

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-ChainList#117]
- [x] vDOT_ - Bifrost Polkadot
- [x] DOT - Bifrost Polkadot => New
- [x] LDOT - Acala
- [x] DOT - Acala
- [x] sDOT - Parallel => New
- [x] DOT - Parallel => New
- [x] DOT - Interlay => New
- [x] DOT - HydraDX => New

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1884-build-1.1.10-2023-09-08T10-16-13UTC.zip

Validation passed for cases:
- Show balance
- Transfer token (approve step)
