### ISSUE TITLE
Add support for USDC

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#119]
USDC is launching on Polkadot in September, please add support for it on Polkadot Asset Hub.
- Asset ID: 1337
- Logo: https://www.figma.com/file/3RzS7xOdFaoQgHwDEOIjHg/Presentation?type=design&node-id=800-11765&mode=design&t=cxjc6W8tOfR1RsEn-4
Let me know if you need more information.

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/cDA6dxdscSdWEfN

Validation passed for cases:
- Show balance
- Transfer token (approve step)
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/6cfc1b0b-d574-41e1-9eb4-22b3ed63b681)
