### ISSUE TITLE
[Snow network] Integrate Snow EVM to SubWallet

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-ChainList#12]
**Describe the task**
Integrate Snow EVM to SubWallet
@Mabel-Nguyen please provide me information of SNOW EVM network

**Comment by Mabel-Nguyen** [comment]
@Sokol142196 @NamPhamc99 Please find the project information below:
- Website: https://icenetwork.io/snow/
- Docs: https://docs.icenetwork.io/build/network-endpoints 

Let me know if you need anything else. Thanks!
