### ISSUE TITLE
Add XCM Support between Kusama and Amplitude (KSM)

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-ChainList#121]
Describe the task
Add XCM Support between Kusama and Amplitude with KSM token

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/6oScnRHFT7otWkJ

Validation passed.
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/ec02bdcd-bdc0-4364-bf17-f33ad4297549)
