### ISSUE TITLE
[VARA] Add staking support for VARA

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#122]
Please add support for VARA staking inside SubWallet.
For VARA mainnet staking, Vara network uses the same staking pallet as other substrate-based chains - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.vara-network.io#/staking/actions

Let me know if you need other information. Thank you!

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/sHWdZ2BFT8wmbZr

Validation passed in cases:
- Show balance
- Show staking item
- Stake and Unstake (approve step)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/WAmMF7s3L5jAD4y
Re-check issues:

- [ ] Min stake to transaction successfully
- [ ] Unstake function
  - Actual: input amount unstake = 5 VARA but result show unstake 10 VARA (check with acc https://vara.subscan.io/account/kGm4tpLSCy2PKtLLyiFkkDv6T2o7bF5bnmXyezxNZbm2TJynm)
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/543bc797-ff16-4140-b187-9701a5acde43)

**Comment by Sokol142196** [comment]
Notes for VARA staking
- Min active stake = 50 VARA
- Existential = 10 VARA
Written on documents but not saved on chain like other networks, so when doing:
- If stake < 10 VARA will result in an error - transaction failed
- If stake = 10 VARA and unstake < 10 VARA will default to unstake all (for example: enter unstake 5 but actually unstake 10)

The next actions:
- Follow the staking item to withdraw unstaked funds
- Follow the next updates from the Vara team
