### ISSUE TITLE
Bittensor (TAO) | Add Functionality

### ISSUE THREAD

**Issue by jameszwifter** [Koniverse/SubWallet-ChainList#125]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: Bittensor is a language for writing numerous decentralized commodity markets under a unified token system. Bittensor aims to direct the power of digital markets towards the creation of society's most important digital commodity - artificial intelligence
- Basic information about your team (as transparent as possible): Founded by Jacob Steeves and Ala Shaabana. Team consists of 20 full-time employees
- Whitepaper (if you have one): https://bittensor.com/whitepaper
- Social media links (telegram, discord, website, linkedin,...): https://t.me/taobittensor, https://discord.gg/GkBXUWeY, bittensor.com, https://www.linkedin.com/company/bittensor
- Any other useful material so we can get to know you better: https://bittensor.com/about
- An email (and element channel if you have one): james@bittensor.com
- Github: https://github.com/opentensor/bittensor
- Any grant information you can provide (W3F Grants, Substrate Builders Program,...) (optional)

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Bittensor
- Type of the blockchain: Substrate-based L1
- Blockchain providers (WS or HTTP). we support both WS and HTTP; wss://entrypoint-finney.opentensor.ai:443
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...): no chainId, no paraId, addressPrefix = 42, symbol = TAO, 9 decimals
- Logo of the blockchain: attached
- Block explorers (if possible): https://scan.bittensor.com/

Note:
- If you want to add a smart contract asset, then you would need to provide proof that your project is active and there are users/holders
- Make sure your logo follow this styling: ![TAO Logo Sep 2023](https://github.com/Koniverse/SubWallet-ChainList/assets/142922312/91e4e64f-bc3b-40e0-82db-d4bd13edec7e)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/6oScnRHFT7otWkJ

Validation passed.
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/0123ad27-0cc3-4566-bc10-136ed97a2f7f)
