### ISSUE TITLE
[USDC] Support native USDC on Polkadot parachains & XCM transfer of USDC 

### ISSUE THREAD

**Issue by djhatrang** [Koniverse/SubWallet-ChainList#126]
Please support native USDC on Polkadot parachains & XCM transfer of native USDC between parachains:

- HydraDX (assetID: 22)
- Acala (announcement: https://twitter.com/AcalaNetwork/status/1704611129627173052)
- Mangata (announcement: https://twitter.com/AcalaNetwork/status/1704611129627173052)
- Moonbeam (announcement: https://twitter.com/MoonbeamNetwork/status/1704122032407904734)
- Interlay (announcement: https://twitter.com/Polkadot/status/1704121057848799606)
- Centrifuge (announcement: https://twitter.com/circle/status/1704119610327646405)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/6oScnRHFT7otWkJ

Validation passed in case: XCM USDC(Polkadot Asset Hub -> HydraDX)
