### ISSUE TITLE
[Dancebox] [Tanssi] Add support for Tanssi testnet - Dancebox

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#128]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Dancebox
- Type of the blockchain (can be Substrate, EVM or both): Substrate
- Blockchain providers (WS or HTTP): wss://fraa-dancebox-rpc.a.dancebox.tanssi.network
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Chain Id: Not applicable
Para Id: 3000
Address prefix: 42
Token Symbol: DANCE
isEthereum: false
- Logo of the blockchain: https://drive.google.com/drive/folders/1HgbjIeRosmJt5nQtDaRjEHTOSPS2hIS-
- Block explorers (if possible)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/6oScnRHFT7otWkJ

Validation passed.
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/20b9216d-4564-49fb-aee3-ac2b73bd90a8)

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/6oScnRHFT7otWkJ

Validation passed
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/a99a9864-7659-4101-8ed1-1a4de3fb9335)
