### ISSUE TITLE
[USDC] Support native USDC on Polkadot parachains & XCM transfer of USDC

### ISSUE THREAD

**Issue by ThaoNguyen998** [Koniverse/SubWallet-ChainList#129]
Support native USDC on Polkadot parachains & XCM transfer of native USDC between parachains:

- Acala (announcement: https://twitter.com/AcalaNetwork/status/1704611129627173052)
- Mangata (announcement: https://twitter.com/AcalaNetwork/status/1704611129627173052)
- Moonbeam (announcement: https://twitter.com/MoonbeamNetwork/status/1704122032407904734)
- Interlay (announcement: https://twitter.com/Polkadot/status/1704121057848799606)
- Centrifuge (announcement: https://twitter.com/circle/status/1704119610327646405)

**Comment by Sokol142196** [comment]
Same as https://github.com/Koniverse/SubWallet-ChainList/issues/130
