### ISSUE TITLE
[Krest network] Integrate Krest network to SubWallet 

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-ChainList#13]
**Describe the task**
Integrate Krest network to SubWallet.
@Mabel-Nguyen please provide me information of Krest network

**Comment by NamPhamc99** [comment]
https://www.peaq.network/

The network is not live yet

**Comment by NamPhamc99** [comment]
Krest is live on Kusama

**Comment by Mabel-Nguyen** [comment]
Hi @NamPhamc99 @Sokol142196 the Peaq team has updated info about Krest network, please see below:

- Name of the blockchain: Krest Network
- Type of the blockchain: Substrate
- Genesis hash: 0xb3dd5ad6a82872b30aabaede8f41dfd4ff6c32ff82f8757d034a45be63cf104c
- Address prefix: 42
- Decimals: 18
- Logo of the blockchain: https://www.figma.com/file/3RzS7xOdFaoQgHwDEOIjHg/Presentation?type=design&node-id=626-14104&mode=design&t=RKtCYmoCTnMB1sD9-4
- Token: KREST
- Logo of the token: https://www.figma.com/file/3RzS7xOdFaoQgHwDEOIjHg/Presentation?type=design&node-id=626-14111&mode=design&t=RKtCYmoCTnMB1sD9-4

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1720-build-1.1.5-2023-08-01T08-03-40UTC.zip

Validation passed for case:
- Turn on/turm off network
- Show balance
- Send token (approve step)

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/84e9f5a3-8bbb-4e6f-934d-ff224285a865)
