### ISSUE TITLE
Support XCM transfer of USDC on Polkadot Parachains

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-ChainList#130]
**Describe the task**
Support XCM transfer of USDC on Polkadot Parachains
Continue https://github.com/Koniverse/SubWallet-ChainList/issues/126

- [ ] Acala (announcement: https://twitter.com/AcalaNetwork/status/1704611129627173052)
- [ ] Mangata (announcement: https://twitter.com/AcalaNetwork/status/1704611129627173052)
- [x] Moonbeam (announcement: https://twitter.com/MoonbeamNetwork/status/1704122032407904734, https://twitter.com/MoonbeamNetwork/status/1721890925763555604)
- [x] Interlay (announcement: https://twitter.com/Polkadot/status/1704121057848799606)
- [ ] Centrifuge (announcement: https://twitter.com/circle/status/1704119610327646405)

**Comment by NamPhamc99** [comment]
- [ ] Why was XCM invented? What problem does it solve?
- [ ] What's the key design principle of XCM?
- [ ] Learn how to make XCM transfer from relaychain to parachain

**Comment by bluezdot** [comment]
- [ ] tích hợp usdc trên các mạng
- [ ] thêm assetRef
- [ ] Kiểm tra trên code

**Comment by bluezdot** [comment]
USDC: 
- [ ] Moonbeam - AssetHub
- [ ] AssetHub - Moonbeam
- [ ] Interlay - AssetHub
- [ ] AssetHub - Interlay
