### ISSUE TITLE
Add support for the sub0 2023 Biodiversity NFT Collection

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#131]
Please add support for the sub0 2023 Biodiversity NFT Collection https://kodadot.xyz/ahp/collection/13

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/4E5bGZEY9zpaeFX

Validation passed

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/fd3248c3-6808-4246-b406-2dd33b697880)
