### ISSUE TITLE
[Gear/Vara Network] Add support for Gear/Vara Network NFTs

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-ChainList#132]
** Please name the issue/PR after this format**
Please integrate Gear NFT. It has its own standards but similar to ERC721
- https://wiki.gear-tech.io/docs/examples/gnft-721/

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/a3n3sAJwCrNowsg

Validation passed in cases:
- Show NFT
- Send NFT: Show message "This feature is not yet available for this NFT" when submit the transaction
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/4e8b2a36-8d8e-4a6b-829c-a6f331d907bf)

![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/dd465c54-2a60-44b9-8a3c-d0088c06e779)
