### ISSUE TITLE
Review and update OnFinality RPC

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-ChainList#135]
**Describe the task**
Review and update OnFinality RPC

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/c098ac83-b67b-4f66-b8cb-9ef4103ecffa)

**Comment by ThaoNguyen998** [comment]
Actual: 
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/3a56b945-937e-4fd1-b503-04a4ae390b52)

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/7yzGrZmakQxT7Y6

Validation passed in these chain
