### ISSUE TITLE
Remove Bobabeam network

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-ChainList#136]
**Describe the task**
Remove Bobabeam network

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/Et7Q2Em4rfKsg2L

Validation passed. 
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/e23e90b4-bd6e-4d04-a166-4c7441592e21)
