### ISSUE TITLE
[EVM] [ZetaChain] [aZETA] ZetaChain EVM-compatible L1 blockchain that connects everything

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-ChainList#137]
[EVM] [ZetaChain] [aZETA] ZetaChain EVM-compatible L1 blockchain that connects everything

**All Information:**

1. Chain specific information: https://www.zetachain.com/docs/reference/testnet/
2. Press Kit: https://drive.google.com/drive/u/0/folders/1wTq2OBSEoRmEvHnvVECl4icmRmENzBla

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/Et7Q2Em4rfKsg2L

Validation passed in case: 
- Show token
- Send token
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/782566f5-cd17-4291-a8d5-ee1768d93699)
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/da0b4aef-d28c-4ea9-bda4-14dab1e04c70)
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/896e14ec-e85d-4ecd-86a0-9e79c591c949)
