### ISSUE TITLE
[Dancebox] [Xcavate] Add support for the Xcavate testnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#138]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team
Xcavate is a protocol designed to provide a less trust more transparency environment in which investors can choose to invest in property direct from real estate developers, removing the need for trusted intermediaries like; banks, solicitors, estate agents or funds.
- Basic information about your team (as transparent as possible)
https://xcavate.io/team/
- Social media links (telegram, discord, website, linkedin,...)
Website: https://xcavate.io/
Twitter: https://twitter.com/xcavateofficial
- Github
https://github.com/orgs/XcavateBlockchain/repositories
- Any grant information you can provide (W3F Grants, Substrate Builders Program,...) (optional)
https://github.com/XcavateBlockchain/Grants-Program/blob/master/applications/Xcavate.md (completed)
https://github.com/XcavateBlockchain/Grants-Program/blob/master/applications/Xcavate2.md (being reviewed)

**If you want to integrate a chain, you would need to provide**
- AppChain
fraa-dancebox-3031-rpc.a.dancebox.tanssi.network
wss://fraa-dancebox-3031-rpc.a.dancebox.tanssi.network
- Token metadata: 
https://polkadot.js.org/apps/?rpc=wss://fraa-dancebox-3031-rpc.a.dancebox.tanssi.network#/settings/metadata
- Logo: 
![X_RGB](https://github.com/Koniverse/SubWallet-ChainList/assets/113659554/288e026b-38ab-425b-a891-ee5c9e19fcaf)

**Please take a look at https://github.com/Koniverse/SubWallet-Chain/blob/master/CONTRIBUTING.md**

**Comment by ThaoNguyen998** [comment]
Version test: http://14.224.158.246:8900/s/Et7Q2Em4rfKsg2L

Validation passed in case: 
- Show token 
- Send token
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/6b2195c1-10db-40cb-8761-f3adc08b753a)
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/a2154950-a8d8-421d-bb84-f352181d1056)
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/117999489/4cfa28bb-d4c7-455d-a90d-b0af1deb7e85)
