### ISSUE TITLE
Add support for Watr Mainnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#139]
Watr has recently launched their mainnet. Please add support for it in SubWallet.
- Blockchain name: Watr Network
- RPC: wss://watr-rpc.watr-api.network
- https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwatr-rpc.watr-api.network#/explorer
- Docs: https://docs.watr.org/
- Logo: same as testnet logo

Let me know if you need further information!

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/FZdYsBEEqrHQckY

Watr mainnet (Substrate)
Validation passed in cases:
- Show token
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/6369d491-8eef-42cc-9ded-cc6ec91e5c34)

- Transfer token (Approve step)

![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/344f7f22-3624-408f-80cc-2d4c22148aba)
