### ISSUE TITLE
Add support for Enjin Relaychain and Enjin Matrixchain

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#140]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: https://enjin.io/company
- Docs: https://docs.enjin.io/enjin-blockchain/overview
- Social media links (telegram, discord, website, linkedin,...)
Website: https://enjin.io/enjin-blockchain
Twitter: https://twitter.com/enjin
- Github: https://github.com/enjin

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain 1: Enjin Replaychain
- Name of the blockchain 2: Enjin Matrixchain (replaces Efinity)
- Type of the blockchain: Substrate
- Blockchain providers (WS or HTTP): 
Enjin Relaychain: https://rpc.relay.blockchain.enjin.io/ 
Enjin Matrixchain: 
https://rpc.matrix.blockchain.enjin.io/
https://enjin-matrix-rpc-1.dwellir.com/
(These can also be accessed via websocket, using the wss:// protocol)

- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...) 
Integration doc: https://enjineer.notion.site/Enjin-Blockchain-Integration-Quickstart-Guide-1c5b0a92a2284d098c3d26e0f8445814
Enjin Relaychain: 
SS58 Prefix: 2135
Enjin Matrixchain (replaces Efinity):
SS58 Prefix: 1110

- Logo of the blockchain: 
Full press kit: https://drive.google.com/drive/folders/1ijlDn_f9PN8GsT9kQfGZR0ObrUgEL2ge?usp=sharing&pli=1
- Block explorers (if possible): https://console.enjin.io/#/explorer

**Comment by NamPhamc99** [comment]
- [ ] Read up about Enjin network? What problem is it targeting? How does it plan to solve that problem?
- [ ] Write a script to get the following information:
       - ss58 prefix
       - genesisHash
       - decimals
       - native token symbol
       - paraId
       - chainId (EVM)

**Comment by Sokol142196** [comment]
Version test: https://164f1573.subwallet-webapp.pages.dev/

Please check the issue:

- [ ] There is no token on the Enjin Relaychain and Enjin Matrixchain


![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/5e02398f-7783-4a25-bca3-b58e4b204e6a)

**Comment by Sokol142196** [comment]
Version test:

Validation passed in cases:
- Show token, network
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/76e9e5f1-f2e2-4ed1-a4d9-3ecbb48dbc56)

- Show balance
- Transfer token (approve transaction with QR signer account)
