### ISSUE TITLE
Update some chain names

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#142]
Please update some chain names as listed below:

- [x] Watr Network -> Watr Testnet
- [x] Watr Network - EVM -> Watr Testnet - EVM
- [x] Mangata Kusama -> Mangata X

**Comment by Sokol142196** [comment]
Version test: https://164f1573.subwallet-webapp.pages.dev/

Validation passed


![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/156479b0-fcd9-4662-935d-0eff575feb66)
