### ISSUE TITLE
Update interface and data for field extraInfo.subscanSlug

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-ChainList#147]
## Update field on Strapi
- [x] Update extraInfo.subscanSlug
- [x] Recheck block explorer URL

**Comment by bluezdot** [comment]
Updated information: https://docs.google.com/spreadsheets/d/1maMCYzi3xqtL3pVl9aIlfQFpw-1ZuJuK6_UfAUUVRXo/edit#gid=0
