### ISSUE TITLE
[Polimec] Add support for Polimec

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#148]
Polimec is Polkadot Parachain #51 (https://parachains.info/details/polimec/). They are going live soon, please help add support for them in SubWallet.

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Polimec
- Type of the blockchain: Substrate
- Blockchain providers: wss://rpc.polimec.org
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
address prefix: 41
symbol: PLMC
Decimals: 10
- Logo of the blockchain: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=313-50&mode=design&t=dY2glzpaWjvsOAr4-4
- Block explorers (if possible) _will be available on Polkascan soon according to their Squid data_
Squid: https://squid.subsquid.io/polimec/graphql

**Comment by NamPhamc99** [comment]
- RPC URL: wss://rpc.polimec.org
- Main Squid: https://squid.subsquid.io/polimec/graphql
- ss58 prefix: 41
- Token: PLMC
- Decimals: 10

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2404
