### ISSUE TITLE
[Subspace] Add support for Subspace Gemini 3g

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#149]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Subspace Gemini 3g
- Type of the blockchain (can be Substrate, EVM or both): Substrate
- Blockchain providers (WS or HTTP). wss://rpc-0.gemini-3g.subspace.network/ws
- Explorer: _updating_

**Comment by Sokol142196** [comment]
Version test: https://a282a8f3.subwallet-webapp.pages.dev/

Validation passed in cases:
- Show network, token
- Show balance
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/843476ab-a16e-47da-b8ef-b23aaa12ba18)

- Transfer (approve step)
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/6b1e750d-31d3-414d-be9d-922672436b65)
