### ISSUE TITLE
Add support for Manta zkAddress & zkAsset

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-ChainList#15]
**Is your feature request related to a problem? Please describe.**
Please integrate Manta zkAddress & zkAsset. Below are their docs:

- https://docs.manta.network/docs/guides/MantaSigner
- https://github.com/Manta-Network/sdk => you should switch to signer_extension branch
- https://www.npmjs.com/package/manta-extension-sdk

**Comment by Sokol142196** [comment]
Supported view ZK tokens.
