### ISSUE TITLE
[Goldberg Testnet] [Avail] Add support for Goldberg testnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#152]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Goldberg Testnet
- Type of the blockchain (can be Substrate, EVM or both) Substrate
- Blockchain providers (WS or HTTP):
https://goldberg.avail.tools/api
wss://goldberg.avail.tools/ws
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Find all info at: https://docs.availproject.org/networks/
- Logo of the blockchain: use the Avail logo
- Block explorers (if possible): https://goldberg.avail.tools/

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/4tfqW7YSo8R9Srn

Validation passed in cases:
- Show token, network
- Show balance
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/ba8b2f0d-f651-487a-b17d-f4b906859a44)

- Transfer token
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/01d9366b-e556-40a0-9de1-4eb8edf8f9ab)
