### ISSUE TITLE
Add logo for custom network GOS

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-ChainList#153]
Support logo for custom network GOS follow up this guild:
https://swtch-labs.gitbook.io/grid-operating-systems-guide/gos-wallet/subwallet

Logo resources (Need resize 160x160 and  update to squirrel format): 
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/11567273/e5595e5c-5b36-41f4-8308-b9585eb5fba5)

**Comment by Sokol142196** [comment]
@saltict this logo apply for GOS network GOST network and GOS/GOST token? Please confirm for me
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/0f8fe1e1-6816-45e4-8009-01b4d7390c32)

**Comment by saltict** [comment]
@Sokol142196 native token of GOS is MGOS
