### ISSUE TITLE
[Bittensor] [TAO] Support TAO in-app staking

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-ChainList#158]
** Please name the issue/PR after this format**
[Bittensor] [TAO] Support TAO in-app staking

**Documents and references:**
- https://bittensor.com/documentation/delegation/delegation
- https://delegate.taostats.io/staking

**Please take a look at https://github.com/Koniverse/SubWallet-Chain/blob/master/CONTRIBUTING.md**

**Comment by nampc1** [comment]
Will be resolved by #2505
