### ISSUE TITLE
[Creditcoin] [CTC] Add block explorer for Creditcoin

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-ChainList#159]
** Please name the issue/PR after this format**

Creditcoin is not available on Subscan yet. Please add their own block explorer: https://creditcoin.subscan.io/

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/H9RjpisWN3zxH6K

Validation passed
![159-chainlist-validation](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/6f1eb510-591e-42ad-90da-211821a8d7c2)
