### ISSUE TITLE
[Energy Web X] Integrate EWX Staging Parachain (testnet)

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-ChainList#160]
** Please name the issue/PR after this format**
[Energy Web X] Integrate EWX Staging Parachain (testnet)

- Name of the blockchain: EWX Staging Parachain
- RPC: wss://ewx-staging-parachain-argon-wmfbanx0xb.energyweb.org/ws
- chainId: 6ab1bd8aed6d5fdcaf347826bfcd0172
- paraId: 2000
- addressPrefix: N/A
- symbol: VT
- Logo of the blockchain:
![ewx-logo](https://github.com/Koniverse/SubWallet-ChainList/assets/102496727/08a9b59e-a579-4f6f-a788-39d4005bfccc)
    
- Block explorers: We don't have explorer yet

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/DJqgQgwnMkyyXZJ

Validation passed in cases:
- Turn on/ Turn off network

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/8121b933-5b7a-4901-b9a7-322ff33fb481)


- Show balance

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/1a815ea8-1674-450d-9035-644a16cf3f5b)


- Transfer token


![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/66c1cc34-4934-4f91-a2df-e5c6e948e57a)
