### ISSUE TITLE
[Energy Web Chain] Integrate EWC EVM chain

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-ChainList#162]
RPC endpoint: http://explorer.energyweb.org/ (it also supports WS)
Read this doc: https://energy-web-foundation.gitbook.io/energy-web/ew-dos-technology-components-2023/trust-layer-energy-web-chain/ewc-guides-and-tutorials/connect-to-energy-web-chain-main-network-with-metamash

Logo: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=2535-201&mode=design&t=VRs5uHpMh00Xyjdl-4

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/DJqgQgwnMkyyXZJ

Validation passed in cases;
- Turn on/ Turn off network
- Show balance
- Transfer token (approve step)
