### ISSUE TITLE
[Energy Web X] Support Energy Web X testnet and mainnet

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-ChainList#163]
** Please name the issue/PR after this format**
[Energy Web X] Support Energy Web X testnet and mainnet

**1. EWX Rococo Testnet**
- RPC: https://public-rpc.testnet.energywebx.com/ (wss://public-rpc.testnet.energywebx.com/ws)
- chainId: ac123be800b7c9a3e3449bb70edd8e3d
- paraId: 3345
- symbol: VT
- logo: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=2535-201&mode=design&t=VRs5uHpMh00Xyjdl-4

**2. Energy Web X**
- RPC: https://public-rpc.mainnet.energywebx.com/ (wss://public-rpc.mainnet.energywebx.com/ws)
- chainId: 5a51e04b88a4784d205091aa7bada002
- paraId: 3345
- symbol: EWT
- logo: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=2535-201&mode=design&t=VRs5uHpMh00Xyjdl-4

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/gJaqEC8qDK4pbYt
- Energy Web X: integrated in v1.1.25 
- EWX Rococo Testnet
Validation passed in cases:
- Turn on/ Turn off network
- Show balance
- Transfer token (approve step)
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/7b9db070-d39b-4e51-a0f1-8cc3f5957f63)
