### ISSUE TITLE
Update USDC on Polygon network 

### ISSUE THREAD

**Issue by S2kael** [Koniverse/SubWallet-ChainList#164]
**Describe the task**
Update USDC on Polygon network

The info of USDC on Polygon in Extension is out of date.
It updates with the name `Bridged USDC` and the symbol `USDC.e`.

Now, Polygon network has native USDC with contract address `0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359`.

**Comment by Sokol142196** [comment]
Version test: http://14.224.158.246:8900/s/gJaqEC8qDK4pbYt

Validation passed in cases:
- Update old USDC to USDC.e
- Add new USDC token with new contract
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/3eab362f-aa13-47ba-9fec-ceea2ff773eb)
