### ISSUE TITLE
[InvArch] Add support for InvArch Network

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#168]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: InvArch
- RPC: wss://invarch-rpc.dwellir.com
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Para ID: 3340
SS58 Prefix: 117
Native asset: VARCH _(transfer is disabled at the moment)_
- Logo of the blockchain: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=28-23&mode=design&t=rgWKFOkdqY7J1dJR-4
- Block explorers (if possible) n/a

**Documents and references:**
Please attach all sources of the information you provided above
- Website: https://invarch.network/
- Github: https://github.com/invarch

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2447
