### ISSUE TITLE
Update chainlist

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-ChainList#171]
Update provider:
- [x] Add providers for Polkadex
- [x] Update endpoint value for provider Parallel of chain Parallel
- [x] Update default provider for Parallel: set to Dwellir

**Comment by Mabel-Nguyen** [comment]
Please help change the network logo of Energy Web X to the EWX logo here: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=2530-264&mode=design&t=QawgeSmjHwGWkOOk-4
