### ISSUE TITLE
[Krest] support in-app staking for KREST

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#175]
Please add in-app staking support for Krest (Kusama Parachain) in SubWallet. Thank you!
- Website: https://krest.peaq.network/
- Github: https://github.com/peaqnetwork
- https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss-krest.peaq.network%2F#/explorer
Let me know if you need further info!

**Comment by bluezdot** [comment]
Add RPC:
- Name: UnitedBloc
- Url: wss://krest.unitedbloc.com/
