### ISSUE TITLE
[Manta] Support XCM transfer between Manta Atlantic and other networks

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#177]
Please add support for XCM transfer between Manta Atlantic and other networks as listed below:
- XCM between Polkadot and Manta Atlantic (DOT)
- XCM between Manta Atlantic and Moonbeam Network (DOT and MANTA)

Let me know if you need further information, thank you!

**Comment by bluezdot** [comment]
- [ ] DOT (Polkadot) <-> DOT (Manta Atlantic)
- [ ] DOT (Manta Atlantic) <-> DOT (Moonbeam)
- [ ] MANTA (Manta Atlantic) <-> MANTA (Moonbeam)

**Comment by bluezdot** [comment]
- [ ] Add token DOT (Manta Atlantic)
- [ ] Add token xcMANTA (Moonbeam)

**Comment by bluezdot** [comment]
- [ ] Add token MANTA (Manta Pacific)

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2508
