### ISSUE TITLE
Add support for PINK token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#179]
- Name of the asset: PINK
- Origin blockchain of the asset: Polkadot Asset Hub
- Is it available on other blockchains? Moonbeam
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
PINK on Polkadot Asset Hub: https://assethub-polkadot.subscan.io/assets/23?tab=holders
PINK on Moonbeam: https://forum.moonbeam.network/t/referendum-36-proposal-to-register-asset-xcpink/1435
- Logo of the token: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=3025-23&mode=design&t=z1pnWV2LIGm9tiaR-4
- Is your asset transferable? yes _(available at launch)_

**Comment by Sokol142196** [comment]
Resolve in https://github.com/Koniverse/SubWallet-Extension/issues/2570
