### ISSUE TITLE
Update chains for Subspace

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-ChainList#180]
- Add support Subspace Gemini 3h (wss://rpc-0.gemini-3h.subspace.network/ws)
- Disable Gemini 2a and Gemini 3f

**Comment by Sokol142196** [comment]
Resolve in https://github.com/Koniverse/SubWallet-Extension/issues/2570

**Comment by bluezdot** [comment]
st8GQpWtFajRK5LJP8XJV4tBKg3yFpXDx9XSJRqjoZeqx6P1v

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2586
