### ISSUE TITLE
[HydraDX] Add support for more tokens on HydraDX

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#181]
Please add support for the following tokens on HydraDX. Thank you!

**Blockchain:** HydraDX
- https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fhydradx-rpc.dwellir.com#/explorer
 
**Tokens:**
- GLMR ([logo](https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=28-272&mode=design&t=WtbhqmAR8yEKwOHI-4))
- ASTR ([logo](https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=897-311&mode=design&t=WtbhqmAR8yEKwOHI-4))
- BNC ([logo](https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=760-42&mode=design&t=WtbhqmAR8yEKwOHI-4))
- INTR ([logo](https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=1020-58&mode=design&t=WtbhqmAR8yEKwOHI-4))

**Comment by bluezdot** [comment]
BNC

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/72647326/fe332eca-75d6-4781-a2e7-e215a6f58e86)


![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/72647326/59934348-bbd9-4186-b083-1f1f2219f441)

**Comment by bluezdot** [comment]
___ASTR___:

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/72647326/b2f0d41a-7479-4165-89e3-0de1326d75f2)


![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/72647326/bc7fc6ca-b930-42f6-8436-aabc7ba83cd0)


priceId: https://www.coingecko.com/en/coins/astar

**Comment by bluezdot** [comment]
___GLMR___:
![Screenshot 2024-03-04 at 12 34 30](https://github.com/Koniverse/SubWallet-ChainList/assets/72647326/c6764556-8e3f-47e6-b377-3e8377c810e8)

![Screenshot 2024-03-04 at 12 35 23](https://github.com/Koniverse/SubWallet-ChainList/assets/72647326/5e253675-cdc6-4021-9d19-9f6700592286)

priceId: https://www.coingecko.com/en/coins/moonbeam

**Comment by bluezdot** [comment]
___INTR___: Add before
