### ISSUE TITLE
[Polimec] Add in-app staking support for PLMC

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#183]
Hi team, please help add in-app staking support for Polimec in SubWallet!
- Staking doc: https://hub.polimec.org/learn/staking

**Comment by bluezdot** [comment]
Account has plmc staking: 59iUooVWNUHjACvKByAtheN7Hi3w9yimTvMMBasnmULjhKsS

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2771
