### ISSUE TITLE
[OKX] Add support for OKX's X1 testnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#184]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: OKX is a global cryptocurrency spot and derivatives exchange and the second biggest crypto exchange by trading volume, serving over 50 million people globally.
- Social media links (telegram, discord, website, LinkedIn,...)
Website: https://www.okx.com/
Twitter: https://twitter.com/okx
- Github: https://github.com/okx

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: OKX X1 testnet
- Type of the blockchain: ZK-powered L2 on Ethereum
- Blockchain providers:
https://testrpc.x1.tech/
https://x1testrpc.okx.com/
- Metadata of the blockchain: https://www.okx.com/x1/docs/getting-started/user-guide/network-information
- Logo of the blockchain: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=3216-263&mode=design&t=WJ53Qo6C5ASj9mKu-4
- Block explorers (if possible) https://www.okx.com/nl/explorer/x1-test

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2658
