### ISSUE TITLE
[Moonbeam] [Astar EVM] Add support for RMRK token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#185]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: RMRK
- Blockchains:
Moonbeam
Astar EVM (As soon as Axelar integrates Astar, the token will be available.)
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
Moonbeam: [0x524d524B4c9366be706D3A90dcf70076ca037aE3](https://moonbeam.moonscan.io/address/0x524d524B4c9366be706D3A90dcf70076ca037aE3)
Astar: [0x524d524B4c9366be706D3A90dcf70076ca037aE3](https://astar.blockscout.com/address/0x524d524B4c9366be706D3A90dcf70076ca037aE3)
- Logo of the token: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=897-212&mode=design&t=WJ53Qo6C5ASj9mKu-4
- Is your asset transferable? Yes

**Documents and references:**
- https://www.rmrk.app/blog/official-announcement-from-rmrk-introducing-the-new-rmrk-token-contract
- https://www.rmrk.app/blog/rmrk-tokens

**Comment by bluezdot** [comment]
Account has RMRK on moonbeam: 0x4b9D84e1395CEdD43e13271435abAB940AFFD142
Account has RMRK on AstarEVM:
