### ISSUE TITLE
[Tangle Network] [TNT] Add support for Tangle Network

### ISSUE THREAD

**Issue by thomivy** [Koniverse/SubWallet-ChainList#187]
**NOTE:** Tangle Network is currently on Testnet but is due to be mainnet within 1.5 months. The information here is for the integration of mainnet unless otherwise specified.

**About Tangle Network**
Tangle Network is a Substrate-based mainnet crafted to deliver decentralized cloud services, emphasizing Multi-Party Computation (MPC) as a Service (MPCaaS). Enabled by validator restaking, Tangle provides an ideal framework for application development that prioritizes privacy through the secure computation of private inputs.

Our platform supports an array of critical services tailored for developers working on advanced Zero-Knowledge (ZK) and cross-chain solutions. Central to that is the fusion of cross-chain interoperability, Ethereum Virtual Machine (EVM) compatibility, sophisticated governance protocols, and ZK services.

These services include zkSNARKS-as-a-Service (zk-SNARKsaaS) and Trusted Setups-as-a-Service, as well as non-ZK MPC services like Threshold Signature Schemes as-a-Service (TSSaaS) and threshold encryption. Together, these strengths set the stage for an era of rapid implementation of privacy-centric applications.

**About Webb**
Webb, founded by visionary Drew Stone, is a development lab committed to redefining blockchain privacy, specializing in premier cross-chain, multi-party computation and zero-knowledge tooling and services. Backed by industry stalwarts like Polychain, Lemniscap, and Commonwealth Labs, and rooted in deep expertise and contributions to the blockchain space.
[https://webb.tools/](https://webb.tools/)  [https://github.com/webb-tools](https://github.com/webb-tools)

- Whitepaper (if you have one)
[Tangle Network Whitepaper ](https://drive.google.com/file/d/1RjkbceBB0E9vR2UFicUYI0kcy3BU5zRX/view?usp=sharing)
- Social media links (telegram, discord, website, linkedin,...)
- - [https://tangle.tools/](https://tangle.tools/)
- - [https://twitter.com/tangle_network](https://twitter.com/tangle_network)
- - [https://twitter.com/webbprotocol](https://twitter.com/webbprotocol)
- - [https://discord.com/invite/cv8EfJu3Tn](https://discord.com/invite/cv8EfJu3Tn)
- - [https://t.me/webbprotocol](https://t.me/webbprotocol)
- - [https://blog.webb.tools/](https://blog.webb.tools/)
- Any other useful material so we can get to know you better
- - **_Testnet_** On Dot Apps:  [https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftestnet-rpc.tangle.tools#/explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftestnet-rpc.tangle.tools#/explorer)
- - _**Testnet**_ Telemetry [https://telemetry.polkadot.io/#/0x3d22af97d919611e03bbcbda96f65988758865423e89b2d99547a6bb61452db3](https://telemetry.polkadot.io/#/0x3d22af97d919611e03bbcbda96f65988758865423e89b2d99547a6bb61452db3)
- An email
- - `hello@webb.tools`
- Github:
- - [https://github.com/webb-tools/tangle](https://github.com/webb-tools/tangle)
- **Runtime Types**: [https://github.com/webb-tools/tangle/blob/main/types/src/interfaces/lookup.ts](https://github.com/webb-tools/tangle/blob/main/types/src/interfaces/lookup.ts)
- Any grant information you can provide (W3F Grants, Substrate Builders Program,...) (optional)
- - We completed SBP.

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain
- - `Tangle Network`
- Type of the blockchain (can be Substrate, EVM or both)
- - ` Substrate with EVM via Frontier`
- Blockchain providers (WS or HTTP). HTTP is preferable for EVM-compatible chains.
- - wss://rpc.tangle.tools
- - http://rpc.tangle.tools
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
      "chainId": `5845`,
      "addressPrefix": `tg`,
      "network": "tangle",
      "displayName": "Tangle Network",
      "symbols": ["TNT"],
      "decimals": [18],
      "standardAccount": "*25519",
      "website": "https://www.tangle.tools/"
- Logo of the blockchain
**Full PNG**
![Tnt Logo](https://github.com/Koniverse/SubWallet-ChainList/assets/38070512/b0146c4b-f634-4542-8146-0d93bc80cd9f)
**Squircle per specifications**
![tangle-network-squircle](https://github.com/Koniverse/SubWallet-ChainList/assets/38070512/625c18ca-2751-4f36-9bdf-fb9dd63affb8)

- Block explorers (if possible)
-- Blockscout for EVM: [https://testnet-explorer.tangle.tools/](https://testnet-explorer.tangle.tools/)

 @Mabel-Nguyen

**Comment by nampc1** [comment]
Thanks for reaching out @thomivy. We'll add support for Tangle asap

**Comment by bluezdot** [comment]
Account has tTNT: 5HDtMSutQ8q6ACBV3BSLzWwR2ukwdaK4nG7qABvfhYZ21wxB
