### ISSUE TITLE
[DENTNet] [DENTX/DENT] Add support for DENTNet

### ISSUE THREAD

**Issue by henrikdent** [Koniverse/SubWallet-ChainList#188]
- A short introduction about your project/ your team:

> At DENT, we’re passionate about making mobile connectivity available for everyone, everywhere. 
> Our mission is to help businesses provide faster, cheaper, and more reliable access to mobile data while ensuring easy, secure, and transparent management of telecommunication services.
> Since 2017, we’ve been at the forefront of cutting-edge solutions and services that leverage the power of eSIM and blockchain, forming partnerships with leading telecommunication companies and experts worldwide.
>
> DENTNet is a global blockchain for telecommunication assets such as mobile data or frequencies.
> Since the '90s, each mobile network operator has run its own software for accounting, subscription management, traffic management, etc.
> Now, many of these services can be provided by a single platform - DENT's global blockchain.

- Basic information about your team (as transparent as possible): 
  - See https://www.dentwireless.com/about Team
- Whitepaper (if you have one): 
  - Original WP: https://assets-global.website-files.com/644a78b7f4eb1d564df391b7/64561e277006e18464610d83_DENT_ICO_Whitepaper.pdf  
- Social media links (telegram, discord, website, linkedin,...)
  - Website: https://www.dentnet.io & https://www.dentwireless.com
  - X/Twitter: https://twitter.com/dentcoin
  - Telegram: https://t.me/dentcoin
  - LinkedIn: https://www.linkedin.com/company/dentwireless/
- An email (and element channel if you have one): 
  - info@dentnet.io
- Github: https://github.com/dentnet/

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: DENTNet
- Type of the blockchain (can be Substrate, EVM or both): Substrate
- Blockchain providers (WS or HTTP): wss://main.dentnet.io/rpc
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...): 
  - Network name: DENTNet
  - Specname: dentnet
  - Native unit: DENTX
  - Decimals: 18
  - Address Prefix: 9807
- Logo of the blockchain: https://static.dentnet.io/Dentnet-network.svg (same logo for native currency)
- Block explorers (if possible): https://main.dentnet.io/explorer/

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: DENT
- Origin blockchain of the asset: Ethereum (ERC20)
- Is it available on other blockchains: Yes, DENTNet
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...):
  - Ethereum: DENT, 8 decimals, contract 0x3597bfD533a99c9aa083587B074434E61Eb0A258
  - DENTNet: DENT, 8 decimals, assetId 1
- Logo of the token: https://static.dentnet.io/DENT%20Token.svg
- Is your asset transferable? Yes
- For stats see https://coinmarketcap.com/currencies/dent/

**Comment by nampc1** [comment]
Thanks for your interest @henrikdent. I'll discuss with my team to support you guys soon

**Comment by bluezdot** [comment]
rpc: wss://rpc.dentnet.io/ws

**Comment by bluezdot** [comment]
Account has DENT, DENTX: dx9Dent8xGGr2F6edRgKRYNfUXF7XZ2q5NHnLUwpxEWdKVrWK
