### ISSUE TITLE
[Phyken Network] [KEN] Add support for Phyken network (testnet)

### ISSUE THREAD

**Issue by Ekaanth** [Koniverse/SubWallet-ChainList#190]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team
   Phyken Network is a  app-chain and DeFi protocol, building an RWA asset fractionalization protocol, particularly emphasizing #GRWA: renewable energies and solar power on the blockchain.
 Phyken Network solutions for RWA complexities:

   ✅ Phyken ID: Authenticity via DIDs & verifiable credentials.
   ✅ AI-based Compliance Engine: Assurance of regulatory adherence.
   ✅ Attester Infrastructure: Validation of owners, assets, and investors.
   ✅ Third-Party Permissionless Audit Framework: Transparent on-chain records for security & efficiency.

- Basic information about your team 
  We have our team mentioned here: https://phyken.network/team
- Whitepaper
  We have our whitepaper here: https://phyken.network/whitepaper
- Social media links
  - Telegram: https://t.me/phykennetwork
  - Twitter: https://twitter.com/phyken_network
  - Discord: https://discord.gg/pPtvPE49Hm
  - Github: https://github.com/Metaquity-Network
  - LinkedIn: https://www.linkedin.com/company/metaquity
- Any other useful material so we can get to know you better
  Parachains.info:  https://parachains.info/details/phyken_network#about
- An email
   @ekaanth : ekaanth@metaquity.xyz

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain : Phyken network Tundra
- Type of the blockchain : Substrate
- Blockchain providers (WS or HTTP). HTTP is preferable for EVM-compatible chains. : wss://rpc.testnet.metaquity.xyz
- Metadata of the blockchain 
   - Network name: Phyken Network
   - Specname: Tundra
   - Native unit: KEN
   - Decimals: 18
   - Address Prefix: 666
- Logo of the blockchain: https://drive.google.com/drive/folders/1FeZ63ibDSMjpM3ZERfaR18kimVU3fobu
- Block explorers : https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.testnet.metaquity.xyz#/explorer

![Phyken Black bg](https://github.com/Koniverse/SubWallet-ChainList/assets/22363352/a3861b91-ae53-4594-b506-6e5da78fa5bf)

![Phyken White bg](https://github.com/Koniverse/SubWallet-ChainList/assets/22363352/d3c8af39-ae14-4828-a78d-75044df6c532)

cc:  @RyanDinh8 @Mabel-Nguyen

**Comment by nampc1** [comment]
Thanks a lot @Ekaanth, we'll process this issue within this week

**Comment by bluezdot** [comment]
Account has KEN: n9WJnct69hv8rZpVdv7T2KnzahjLBw1XPW4H1TNNYorYAShwi

**Comment by Ekaanth** [comment]
@bluezdot Yes it has, 
if you like to test then you can check `n9TZsFN5TSBsU7W4xwcRxyxzMhAwL2ireBqRNTpBm1xjB3LwA`
