### ISSUE TITLE
[Astar] Add support for Astar zkEVM

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#191]
Hi team, Astar has launched Astar zkEVM - an Ethereum Layer 2 scaling solution leveraging Polygon's zk technology.
Please add in-app support for it.

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Astar zkEVM
- Type of the blockchain: zkEVM
- Metadata, provider, explorer, of the blockchain:
Please see: https://docs.astar.network/docs/learn/zkEVM/quickstart
- Logo of the blockchain: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=3423-18607&mode=design&t=ykAwVACYZI8JT9ne-4
ASTR token logo: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=897-311&mode=design&t=ykAwVACYZI8JT9ne-4

**Comment by bluezdot** [comment]
Account has ETH: 0x7D6C9B97d8959717F44e71DDa19136c37Ed97501
