### ISSUE TITLE
[Polkadot Asset Hub] Add support for DED token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#193]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: DED
- Origin blockchain of the asset: Polkadot Asset Hub
- Metadata of the asset
See: https://assethub-polkadot.subscan.io/assets/30
- Logo of the token: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=3232-342&mode=design&t=q0H03eJaezg6NQwH-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Can you provide a price key? n/a

**Comment by bluezdot** [comment]
Account has DED: 5E9xoBFbfLUBiHKSGT3UPqZsDnKCv5YykazuWexqbG1STSLN

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2771
