### ISSUE TITLE
Add support for Creditcoin cc3 testnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#195]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Creditcoin testnet (cc3 Substrate)
- Type of the blockchain: Substrate
- Blockchain providers: wss://rpc.cc3-testnet.creditcoin.network
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
https://cc3-docs.creditcoin.network/
- Logo of the blockchain: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=1545-15&mode=design&t=TIzEG5NEUfLwVatg-4
- Block explorers (if possible) https://creditcoin3-testnet.subscan.io/

**Comment by bluezdot** [comment]
account has CTC: 5EYCAe5g8RCk5pv3ANvj1GjnNW9VgZJ73JD4yuVudqhTuDnJ
