### ISSUE TITLE
[OKX] Add support for X Layer mainnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#198]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: X Layer
- Type of the blockchain: ZK-powered L2 on Ethereum
- Blockchain providers:
[https://rpc.xlayer.tech/](https://rpc.xlayer.tech/)
[https://xlayerrpc.okx.com/](https://xlayerrpc.okx.com/)
- Metadata of the blockchain: https://www.okx.com/xlayer/docs/getting-started/user-guide/network-information
- Logo of the blockchain: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=3216-263&mode=design&t=bp5dGmcAqkNu30vM-4
- Block explorers: 
https://www.okx.com/explorer/xlayer
https://wwww.oklink.com/xlayer

**Comment by bluezdot** [comment]
Account has OKB: 0xe7a9a370747aab5e7ff1C621a9C337Ca5b8dEbAd

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2851
