### ISSUE TITLE
[Astar zkEVM] Add support for ASTR token on Astar zkEVM

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#199]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: ASTR
- Origin blockchain of the asset: Astar zkEVM
- Metadata of the asset:
https://astar-zkevm.explorer.startale.com/token/0xdf41220C7e322bFEF933D85D01821ad277f90172
https://docs.astar.network/docs/build/zkEVM/canonical-zkevm-contracts/
- Logo of the token: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=897-311&mode=design&t=bp5dGmcAqkNu30vM-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? https://www.coingecko.com/en/coins/astar

**Comment by bluezdot** [comment]
Account has ASTR: 0x5a3319058425EE24A2842a24c6f0339d999B9f46

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2851
