### ISSUE TITLE
[Blockchain] Humanode - HMND (Substrate) / eHMND (EVM) - New network/token integration

### ISSUE THREAD

**Issue by HMPrincessFiona** [Koniverse/SubWallet-ChainList#200]
** Please name the issue/PR after this format**
[Blockchain] Humanode - HMND (Substrate) / eHMND (EVM) - New network/token integration

**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: Humanode is the first crypto-biometric network where one human = one node. Instead of PoW or PoS, Humanode is built on Proof-Of-Uniqueness and Proof-of-Existence of human beings. To deploy a node a validator must go through private biometric authentication that verifies his uniqueness and existence through computer vision. A public permissionless financial network based on consensus between human nodes who share the fees and ownership of the network in an equal manner.
Live on mainnet since 2022, built on Polka sdk, EVM-compatible.
humanode.io
- Basic information about your team (as transparent as possible) - Humanode runs on a team 20 dedicated people working remotely across the globe to create ultimate-level development in blockchain and bring true decentralization to crypto.
https://humanode-network.notion.site/4dd0b16c8fb4422c94bcb23f8672f005?v=dee30bd0fced433aa37a241e8f5891c4
- Whitepaper - https://papers.humanode.io/whitepaper.pdf
- Social media links: Telegram: https://t.me/humanodes | Ann: https://t.me/humanode | X https://twitter.com/humanode_io | LinkedIn https://www.linkedin.com/company/human-node/ | Discord https://link.humanode.io/chat | YouTube: https://www.youtube.com/channel/UCluI64-yFeEv8DmBucI74eQ
- Any other useful material so we can get to know you better Website: https://humanode.io/ | Humanode 101: https://blog.humanode.io/tag/humanode-101/ | Blog: http://blog.humanode.io/ | Blockchain explorer: https://humanode.subscan.io/ 
- An email core@humanode.io
- Github https://github.com/humanode-network
- Any grant information you can provide (W3F Grants, Substrate Builders Program,...) (optional)

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain Humanode
- Type of the blockchain (can be Substrate, EVM or both) Both
- Blockchain providers (WS or HTTP). HTTP is preferable for EVM-compatible chains.  https://link.humanode.io/docs |
https://gitbook.humanode.io/docs/chains
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...) EVM Chain ID: 5234 (0x1472 in hex)
SS58 prefix: 5234
Symbol: HMND (Substrate) / eHMND (EVM)
- Logo of the blockchain https://drive.google.com/drive/folders/1VzlxJyFOhbieyDZ5DinLfHKDHxjJQrIt 
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/99395268/6cc9d2bb-4356-4a9a-aede-6fcf163fa465)

- Block explorers (if possible) https://humanode.subscan.io/

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Humanode
- Origin blockchain of the asset: Humanode
- Is it available on other blockchains? No for now. 
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...): HMND - native asset on native chain, eHMND - native asset of EVM module,  and there is also WeHMND - a wrapped version of eHMND with contract address 0x0000000000000000000000000000000000000802 on Humanode EVM, 18 decimals all of them.
- Logo of the token https://drive.google.com/drive/folders/1VzlxJyFOhbieyDZ5DinLfHKDHxjJQrIt 
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/99395268/30895e22-e27b-4960-a47e-fd29e47386d7)
- Is your asset listed on any exchange? Can you provide a price key? (we use price service from Coingecko) https://www.coingecko.com/en/coins/humanode

Note:
- If you want to add a smart contract asset, then you would need to provide proof that your project is active and there are users/holders
- Make sure your logo follow this styling: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/Polkadot-Project-Logo?node-id=13-2096&t=dwcwfywiIfHXXiBv-0

**Documents and references:**
Please attach all sources of the information you provided above

**Please take a look at https://github.com/Koniverse/SubWallet-Chain/blob/master/CONTRIBUTING.md**

**Comment by nampc1** [comment]
Hello @HMPrincessFiona, nice to meet you. Thanks for opening this issue, we'll work on this asap

**Comment by bluezdot** [comment]
Account has HMND: hmpjxWzgDyF4p3wssdyRH23Wd7kBBgeskZyY2ysoWY4WFuS2G
