### ISSUE TITLE
[Acurast] Add support for Acurast Canary

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#203]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Acurast Canary
- Type of the blockchain: Substrate
- Metadata of the blockchain: https://polkadot.js.org/apps/?rpc=wss://acurast-canarynet-ws.prod.gke.papers.tech#/settings/metadata
- Logo of the blockchain: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=28-537&mode=design&t=O92rrh8nqIZCfPjt-4
- Docs: https://docs.acurast.com/

**Comment by bluezdot** [comment]
Account has cACU: 5GTapMA1Umgafc8UMPu6n5caHpiyuiEfoACUnZwSSp4aGMAr

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2890
