### ISSUE TITLE
[Asset Hub] [HydraDX] Add support for token BEEFY

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#205]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: BEEFY
- Origin blockchain of the asset: Polkadot Asset Hub
- Is it available on other blockchains? HydraDX
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
https://assethub-polkadot.subscan.io/assets/420?tab=holders
- Logo of the token: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=3818-2858&mode=design&t=XnfviCbj31Iu3NF4-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? n/a

**Comment by bluezdot** [comment]
Account has beefy on asset hub, hydradx: 5DsjARhzdCR9dQZP8iaBWGZxM7RPKDofBvC4GTUATs1rLz9V

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/2890
