### ISSUE TITLE
[Base Mainnet] Add support for PINK token

### ISSUE THREAD

**Issue by bluezdot** [Koniverse/SubWallet-ChainList#211]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Pink
- Origin blockchain of the asset: Base Mainnet
- Metadata of the asset:
[https://assethub-polkadot.subscan.io/assets/42069?tab=transfer
https://assethub-polkadot.subscan.io/xcm_message/polkadot-175099652f77164700b7d804acf37c196030dd9b](https://basescan.org/token/0x66fc31b3233c7c001bdd21ff6e5e66fa08ef85d0)
- Is your asset transferable? Yes
- Is your asset listed on any exchange? n/a

**Comment by bluezdot** [comment]
Account has PINK on Base Mainnet: 0xB9D10940Dae76C3e50d422C754009eEDa22b4eA0

**Comment by haiyenvu23** [comment]
Version test : http://file.cdmteck.com/s/AonBXDHkteZaJNs
Data test : 0xB9D10940Dae76C3e50d422C754009eEDa22b4eA0

Validation passed in case :

- Displays the correct balance of the account when on network


![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/631ad31f-1d8d-466c-bba9-e7670d41a55b)



- Can perform Send/Receive tokens

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/215b9874-c6be-4f77-a3c4-2663011c7fab)


- Check case when updated version

- Display correct token information

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/28d25a7b-4c9a-4768-8c59-802364b69bad)
