### ISSUE TITLE
[DBChain] [DBC && DLC] Integrate DBC and DLC tokens from the DBChain network into Subwallet

### ISSUE THREAD

**Issue by HanSXY** [Koniverse/SubWallet-ChainList#212]
[DBChain] [DBC && DLC] Integrate DBC and DLC tokens from the DBChain network into Subwallet

First time integration with Subwallet
- DeepBrain Chain is the world's first distributed GPU cloud computing platform driven by blockchain technology, aimed at reducing 70% of the computing costs in the artificial intelligence industry. DBC is a designated digital currency for computing power rental circulation.
-  [Whitepaper](https://www.deepbrainchain.org/DeepBrainChainWhitepaper_en.pdf)
- Social media
   - [Twitter](https://twitter.com/DeepBrainChain) 
   - [Youtube](https://www.youtube.com/@deepbrainchain) 
   - [Reddit](https://www.reddit.com/r/DBC_Council/) 
   - [Telegram](https://t.me/deepbrainchainglobal) 
- Any other useful material so we can get to know you better
   - [Website](https://www.deepbrainchain.org/) 
- An email [service@deepbrainchain.org](mailto:service@deepbrainchain.org)
- Github 
   - [DeepBrainChain](https://github.com/DeepBrainChain)

**If you want to integrate a chain, you would need to provide**
- DBChain
- Type of the blockchain: Substrate
- Blockchain providers
   Mainnet: wss://info1.dbcwallet.io
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
  - Ticker: DBC
  - Decimals: 15
  - Address format: Polkadot
  - Smart Contract Address: 0x1F735f84b07cc20E9aC471C291a87b5A2428d518
- Logo of the blockchain
  
![dbchain](https://github.com/Koniverse/SubWallet-ChainList/assets/45001948/d7ddab77-6737-4529-ad61-d5269686a13b)

- Block explorers
  - [Mainnet](https://www.dbcwallet.io/)

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
In addition to integrating DBC, we also hope to add DLC tokens, which belong to assets on DBC Mainnet
- Name of the asset： DeepLink Coin
- Origin blockchain of the asset: DBChain
- Is it available on other blockchains?
- Metadata of the asset
  -  Sybmol: DLC
  -  Decimals:  8
  -  AssetId: 88
- Logo of the token
![91b6ec88c898f6e84ed85638502653a](https://github.com/Koniverse/SubWallet-ChainList/assets/45001948/1a2abe6a-a650-4cb2-ad77-893e7354a175)

- Is your asset transferable? 
 Yes

**Comment by Mabel-Nguyen** [comment]
DBC token on Coingecko: https://www.coingecko.com/en/coins/deepbrain-chain
