### ISSUE TITLE
[Commune AI] [COMAI] Add support for Commune AI blockchain and COMAI token (Mainnet)

### ISSUE THREAD

**Issue by anonbitco** [Koniverse/SubWallet-ChainList#213]
- Short intro: 
Commune AI is a protocol that aims to connect all developer tools into one network, fostering a more shareable, reusable, and open economy. It follows an inclusive design philosophy that is based on being maximally unopinionated. This means that developers can leverage Commune as a versatile set of tools alongside their existing projects and have the freedom to incorporate additional tools that they find valuable.
- Team Intro: Salvatore Vivona, Luca Vivona
- Team Email: 
- Whitepaper: https://ai-secure.github.io/DMLW2022/assets/papers/7.pdf
- Social links:
✅ Twitter: https://twitter.com/communeaidotorg
✅ Telegram: https://t.me/communecommunity
✅ Discord: https://discord.com/invite/A8JGkZ9Dmm
✅ Github: https://github.com/commune-ai

If you want to integrate a chain, you would need to provide

- Blockchain integration:
- Name: Commune AI
- Type: Substrate
- Blockchain provider: wss://commune-api-node-1.communeai.net
- Metadata:
✅ Network name: commune
✅ Native unit: C
✅ Decimals: 9
✅ Address Prefix: 42
- logo: 
![commune logo ](https://github.com/Koniverse/SubWallet-ChainList/assets/81495279/ea62f19f-daec-4c51-89cb-3a5935e17d7f)
- explorer: https://explorer.communeai.net/#/explorer/

Asset integration:
- name: COMAI
- Origin blockchain: Commune AI
- Available in other: wCOMAI (ETH), wCOMAI (SOL)
- Metadata: network name: commune, symbol: C, decimal: 9
- logo: 
![commune logo ](https://github.com/Koniverse/SubWallet-ChainList/assets/81495279/c900c5e2-f696-4137-9f94-9742d3b00da1)
transferable: Yes
- Exchanges: 
✅ Uniswap: https://app.uniswap.org/swap?outputCurrency=0xc78B628b060258300218740B1A7a5b3c82b3bd9f&chain=mainnet
✅ MEXC: https://www.mexc.com/exchange/COMAI_USDT
✅ CoinEx: https://www.coinex.com/en/exchange/comai-usdt

**Comment by Mabel-Nguyen** [comment]
DBC token on Coingecko: https://www.coingecko.com/en/coins/deepbrain-chain

**Comment by bluezdot** [comment]
Account has C: 5GjKMbB5AGibM3W2pNY6H9rLMTCkBMTvKMkZhPLJGdo1shMt

**Comment by anonbitco** [comment]
just want to make sure: ticker for token is COMAI (not C, it is only the symbol, metadata)

**Comment by bluezdot** [comment]
> just want to make sure: ticker for token is COMAI (not C, it is only the symbol, metadata)

Thanks you, @anonbitco!
