### ISSUE TITLE
[Avail Turing] Support Avail Turing

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-ChainList#215]

**Comment by bluezdot** [comment]
Account has token: 5Fpz1npqvo299oacoLVhV7qrfKBbgFbbbNFf4fjF56yGkNqg

**Comment by bluezdot** [comment]
Account has staking: 5EykgS719SnRW1xPnUswwwVsGpoW3K7snDBM6acRyK628Hc5

**Comment by Sokol142196** [comment]
Version test: http://file.cdmteck.com/s/MSWDc7txkiB5ynK

Validation passed
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/08ce8234-ae3b-4008-b597-b544e3b30ea9)
