### ISSUE TITLE
[Curio] Add support for Curio Parachain

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#217]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: Curio is a Kusama Parachain. 
Curio chain is positioned primarily as a RWA Appchain - a network for the tokenization of real-world assets.
- Basic information about your team: https://www.linkedin.com/company/curioag
- Whitepaper: https://wiki.parachain.curioinvest.com/
- Social media links:
Website: https://curioinvest.com/
Twitter: https://twitter.com/curio_invest
App: https://capitaldex.exchange/
- Github: https://github.com/CurioTeam

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Curio
- Metadata of the blockchain: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain.curioinvest.com%2F#/explorer
- Logo of the Curio Chain: [[link](https://www.figma.com/file/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?type=design&node-id=6005-13&mode=design&t=C6qxyMBQa2N6qRMK-4)]
- Logo of the CGT token: [[link](https://www.figma.com/file/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?type=design&node-id=6005-2599&mode=design&t=C6qxyMBQa2N6qRMK-4)]

**Comment by bluezdot** [comment]
Ac5HWQVcNPBKR7C9tPmmiouSymXNix7GTUXYwpRkGJkaJ8wsL9

**Comment by Sokol142196** [comment]
resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3020
