### ISSUE TITLE
add support for Pendulum Amplitude assets

### ISSUE THREAD

**Issue by annatekl** [Koniverse/SubWallet-ChainList#220]
This request is for adding support for assets registered on Pendulum

| Asset name  | Origin blockchain |Price Key |Is it available on other blockchains? |Is your asset transferable? |
| ------------- | ------------- |------------- |------------- |------------- |
| XLM.s | Stellar|https://www.coingecko.com/en/coins/stellar |No|Yes |
| EURC.s | Stellar| |No|Yes |
| BRL.s | Stellar| |No|Yes |
| AUDD.s | Stellar| https://www.coingecko.com/en/coins/novatti-australian-digital-dollar|No|Yes |
| NGNC.s | Stellar| |No|Yes |
| HDX | HydraDX|https://www.coingecko.com/en/coins/hydradx |Yes|n/a |
| GLMR | Moonbeam|https://www.coingecko.com/en/coins/moonbeam |Yes|n/a |
| PINK | AssetHub| |Yes|n/a |
| USDC.s | Stellar|https://www.coingecko.com/en/coins/usdc |Yes|Yes |
| USDC | AssetHub |https://www.coingecko.com/en/coins/usdc|Yes |No |
| USDT | AssetHub |https://www.coingecko.com/en/coins/tether|Yes |n/a |
| BRZ | Moonbeam |https://www.coingecko.com/en/coins/brazilian-digital-token|Yes |n/a |

This request is for adding support for assets registered on Amplitude

| Asset name  | Origin blockchain |Price Key |Is it available on other blockchains? |Is your asset transferable? |
| ------------- | ------------- |------------- |------------- |------------- |
| XLM | Stellar|https://www.coingecko.com/en/coins/stellar |No|Yes |
| AUDD | Stellar| |No|Yes |
| EURC | Stellar| |No|Yes |
| BRL | Stellar| |No|Yes |
| NGNC | Stellar| |No|Yes |
| USDC | Stellar|https://www.coingecko.com/en/coins/usdc |Yes|Yes |
| USDT | AssetHub |https://www.coingecko.com/en/coins/tether|Yes |n/a |

**Asset metadata**

XLM:
```
Asset id: {Stellar: StellarNative}
decimals: 12
name: Stellar Lumen
symbol: XLM.s
```

EURC:
```
Asset id: {
          AlphaNum4: {
            code: EURC
            issuer: 0x2112ee863867e4e219fe254c0918b00bc9ea400775bfc3ab4430971ce505877c
          }
decimals: 12
name: Stellar EURC
symbol: EURC.s
```

BRL:
```
Asset id: {
          AlphaNum4: {
            code: 0x42524c00
            issuer: 0xeaac68d4d0e37b4c24c2536916e830735f032d0d6b2a1c8fca3bc5a25e083e3a
          }
decimals: 12
name: Stellar BRL
symbol: BRL.s
```

NGNC: 
```
Asset id: {
        Stellar: {
          AlphaNum4: {
            code: NGNC
            issuer: 0x241afadf31883f79972545fc64f3b5b0c95704c6fb4917474e42b0057841606b
          }
decimals: 12
name: Stellar NGNC
symbol: NGNC.s
```

AUDD:
```
Asset id: {
        Stellar: {
          AlphaNum4: {
            code: AUDD
            issuer: 0xc5fbe9979e240552860221f4fe2f2219f35e40458b8b58fc32da520a154a561d
          }
decimals: 12
name: Stellar AUDD
symbol: AUDD.s
```

USDC:
```
Asset id: {
        Stellar: {
          AlphaNum4: {
            code: USDC
            issuer: 0x3b9911380efe988ba0a8900eb1cfe44f366f7dbe946bed077240f7f624df15c5
          }  
decimals: 12
name: Stellar USDC
symbol: USDC.s
```
USDC:
```
Asset id: {XCM: 2}  
decimals: 6
name: USD Coin
symbol: USDC
```
USDT:
```
Asset id: {XCM: 1}  
decimals: 6
name: Tether USD
symbol: USDT
```

HDX:
```
Asset id: {XCM: 8}  
decimals: 12
name: HydraDX
symbol: HDX
```

GLMR: 
```
Asset id: {XCM: 6}  
decimals: 18
name: Glimmer
symbol: GLMR
```

PINK:
```
Asset id: {XCM: 7}        
decimals: 10
name: PINK
symbol: PINK
```

Icons:
HDX:
repo_url: (https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/b49b26fa-900c-4e24-8d8b-8dfe69a6e037)
PINK:
repo_url: (https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/6957083c-7eb5-4ed7-9627-cac61e373ac5)
AUDD:
repo_url: (https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/d75dcd1b-dd5e-4ed7-9dea-c92c9d599051)
BRL:
repo_url: (https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/0fb07caf-bc51-44d9-b84e-fa8953830637)
EURC:
repo_url: (https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/1f258365-f5bf-416e-8c9e-c33fb0745eba)
NGNC:
repo_url: (https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/3f250c0e-6ec3-405d-a640-d802ba17d612)
XLM:
repo_url: (https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/bea840e8-bf07-4172-a8ba-abe3a1bfce03)
GLMR:
repo_url: (https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/03791ebe-8f22-4229-b363-67ea0f75aed3)
USDC:
Repo_url: (https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/4427ecbf-46fb-4317-88e0-3f9f41a5f69f)
USDT:
Repo_url(https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/8fb60188-246a-40fd-8e33-3e46191108b1)
Repo_url(https://github.com/Koniverse/SubWallet-ChainList/assets/138758794/115c822c-e5fc-4969-96b6-56ace28005d0)

**Comment by nampc1** [comment]
Thanks @annatekl for the super detailed issue. We'll work on it asap. Have a nice day

**Comment by bluezdot** [comment]
Noted: Asset with `Asset id: {XCM: 2}` on Amplitude is not USDC

**Comment by annatekl** [comment]
USDC only to be supported on Amplitude @bluezdot

**Comment by bluezdot** [comment]
Just to confirm @annatekl,
Op1: Use USDC.s for both Amplitude and Pendulum.
Op2: Use USDC.s for Amplitude; USDC for Pendulum.

Is it Op1?

**Comment by annatekl** [comment]
I updated the table so USDC.s just for Amplitude

**Comment by annatekl** [comment]
I did an update to the assets, added USDC (Asset Hub), BRZ and USDT. For the BRZ icon i will provide in the meantime @bluezdot

**Comment by bluezdot** [comment]
I receive the information. Ty @annatekl

**Comment by bluezdot** [comment]
We're going to have a release today, so I decided on the current assets above. 
If there are any new updates, let us know, we'll update them in the next release.
@annatekl
