### ISSUE TITLE
[BOB] Add support for BOB and tokens on BOB

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#221]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: BOB is a hybrid L2 powered by Bitcoin and Ethereum
- Docs: https://docs.gobob.xyz/
- Social media links:
Website: https://www.gobob.xyz/
Twitter: https://twitter.com/build_on_bob
Telegram: https://t.me/gobobxyz
Discord: https://discord.com/invite/gobob
- Github: https://github.com/bob-collective/bob

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: BOB
- Provider: https://rpc.gobob.xyz/
- Metadata: 
Chain ID: 60808
Gas Token: ETH
Decimals: 18
PriceID: ethereum
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6092-68&t=HW7m3ptEHZzKnQxz-4
- Block explorers: https://explorer.gobob.xyz/

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
1. wBTC
- Name of the asset: wBTC
- Origin blockchain of the asset: BOB
- Is it available on other blockchains? Yes
- Metadata of the asset: 0x03C7054BCB39f7b2e5B2c7AcB37583e32D70Cfa3
https://explorer.gobob.xyz/token/0x03C7054BCB39f7b2e5B2c7AcB37583e32D70Cfa3
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-478&t=HW7m3ptEHZzKnQxz-4
- Is your asset transferable? Yes

2. USDT
- Name of the asset: USDT
- Origin blockchain of the asset: BOB
- Is it available on other blockchains? Yes
- Metadata of the asset: 0x05D032ac25d322df992303dCa074EE7392C117b9
https://explorer.gobob.xyz/token/0x05D032ac25d322df992303dCa074EE7392C117b9
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-490&t=HW7m3ptEHZzKnQxz-4
- Is your asset transferable? Yes

**Comment by bluezdot** [comment]
Account has wBTC: 0x93d2f4f3a0445AA808c99cbD6bA05236a895379f
Account has USDT: 0xED3c678f04D92c78C101154A271A50ad9089F443

**Comment by Sokol142196** [comment]
Resolved in https://github.com/orgs/Koniverse/projects/2/views/73#:~:text=Current-,Update%20chainlist,-%233040
