### ISSUE TITLE
Add support SQD token for Arrbitrum

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-ChainList#222]
Describe the task
Add support SQD token for Arrbitrum
- Contract: https://arbiscan.io/address/0x1337420ded5adb9980cfc35f8f2b054ea86f8ab1
- Icon: https://subsquid.io/logo.png

**Comment by bluezdot** [comment]
Account has SQD: 0x737cEe5F01447011A00e51028A62a3c4B619CCE3

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3055
