### ISSUE TITLE
[Moonbeam] Add support for STINK token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#223]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: STINK
- Origin blockchain of the asset: Moonbeam
- Is it available on other blockchains? Yes
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
https://moonscan.io/token/0xFffFffFf54c556bD1d0F64ec6c78f1B477525E56
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=3906-2850&t=6UOKvqDOZy2YJMWG-4
- Is your asset transferable? Yes

**Documents and references:**
https://docs.moonbeam.network/builders/interoperability/xcm/xc20/overview/

**Comment by bluezdot** [comment]
Account has xcSTINK: 0x8dEA19fC09b6fFB2DbdfCbBA7FA880d9b97Daf39

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3088
