### ISSUE TITLE
Add support for WUD token on HydraDX and Polkadot Asset Hub

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#224]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Gavun Wud
- Blockchain of the asset: Polkadot Asset Hub, HydraDX
- Metadata of the asset:
PAH: https://assethub-polkadot.subscan.io/assets/31337
HydraDX: https://hydradx.subscan.io/custom_token?unique_id=asset_registry%2Ff68a68d6f6c10a5f66173d06e15cd6306da2c024
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6117-1685&t=cgUWHIceKsOIekmk-4
- Is your asset transferable? Yes

**Comment by bluezdot** [comment]
Account has WUD (statemint): 158hDxiKxLZvsTJEp6KyzGFwiEREsp146P8LDSM9CVKyevK3

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3088
