### ISSUE TITLE
Add support for WIFD on HydraDX and Polkadot Asset Hub

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#225]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Dog Wif Dots (WIFD)
- Blockchain of the asset: Polkadot Asset Hub, HydraDX
- Metadata of the asset:
PAH: https://assethub-polkadot.subscan.io/assets/17
HydraDX: https://hydradx.subscan.io/custom_token?unique_id=asset_registry%2Fdb3d1fb8dd4a4665a1d1907dfbd3e4d11e69b3d4
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6117-1684&t=cgUWHIceKsOIekmk-4
- Is your asset transferable? Yes

**Comment by bluezdot** [comment]
Account has WIFD: 158hDxiKxLZvsTJEp6KyzGFwiEREsp146P8LDSM9CVKyevK3

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3088
