### ISSUE TITLE
[Linea] Add support for Linea

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#226]
**If this is your first time integrating, the following information is required**
- A short introduction: Linea is an EVM equivalent zkEVM rollup offering fast finality, high throughput, low gas fees and the security of Ethereum settlement.
- Social media links:
Twitter: https://x.com/LineaBuild
Website: https://linea.build/
- Any other useful material so we can get to know you better:
https://docs.linea.build/
- Github: https://github.com/Consensys

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Linea
- Type of the blockchain: zkEVM
- Blockchain providers: https://rpc.linea.build/
- Metadata of the blockchain: 
https://docs.linea.build/developers/quickstart/info-contracts
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6119-1890&t=cgUWHIceKsOIekmk-4
- Block explorers: https://lineascan.build/

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3088
