### ISSUE TITLE
Add support for Common LP Drops and Common Staking Drops

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#227]
- [x] Common LP Drops 
  - Name of the asset: Common LP Drops
  - Origin blockchain of the asset: Aleph Zero
  - Metadata of the asset: 5CJ3DZ4RM4j2cPpQ49ywYiAgDYaTqk7hPud6Y1J1WY8qwDfb
  - Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6137-403&t=yOKrKHHD7yBPPgpR-4
  - Is your asset transferable? No

- [x] Common Staking Drops 
  - Name of the asset: Common Staking Drops
  - Origin blockchain of the asset: Aleph Zero
  - Metadata of the asset: 5DPzHtsvZHtUaGzzKqrxa2JLgpHtEaSPn9mfyNAjX12Vunts
  - Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6137-404&t=yOKrKHHD7yBPPgpR-4
  - Is your asset transferable? No

Explorer: https://ascan.alephzero.org/common (accessible from May 21st)

**Comment by bluezdot** [comment]
Account has CLD: 5CJ3DZ4RM4j2cPpQ49ywYiAgDYaTqk7hPud6Y1J1WY8qwDfb
No holders for CLS

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3055
