### ISSUE TITLE
[Aleph Zero] Add support for bridged tokens

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#228]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
1. WETH
- 5EoFQd36196Duo6fPTz2MWHXRzwTJcyETHyCyaB3rb61Xo2u
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=142-50&t=MbdErwLkctibc846-4
- https://www.coingecko.com/en/coins/ethereum
2. WBTC
- 5EEtCdKLyyhQnNQWWWPM1fMDx1WdVuiaoR9cA6CWttgyxtuJ
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-478&t=MbdErwLkctibc846-4
- https://www.coingecko.com/en/coins/bitcoin
3. USDT
- 5Et3dDcXUiThrBCot7g65k3oDSicGy4qC82cq9f911izKNtE
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-490&t=MbdErwLkctibc846-4
- https://www.coingecko.com/en/coins/tether
4. USDC
- 5FYFojNCJVFR2bBNKfAePZCa72ZcVX5yeTv8K9bzeUo8D83Z
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-489&t=MbdErwLkctibc846-4
- https://www.coingecko.com/en/coins/usdc

**Documents and references:**
[token.json](https://github.com/Koniverse/SubWallet-ChainList/files/15388957/token.json)

**Comment by bluezdot** [comment]
Account has WETH: 5HaM6dHg3ymuQ6NSCquMkzBLLHv9t1H4YvBDMarox37PbusE
Account has WBTC: 5EPfFLxKMcuCTXowaeydPTE1nXfnyrskpVYxaSUmgqf4cfhb
Account has USDT: 5CiP96MhEGHnLFGS64uVznrwbuVdFj6kewrEZoLRzxUEqxws 
Account has USDC: 5C6s2qJAG5dCmPvR9WyKAVL6vJRDS9BjMwbrqwXGCsPiFViF
