### ISSUE TITLE
[Aleph Zero] Add support for Ink Whale token INW2

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#229]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: INW2
- Origin blockchain of the asset: Aleph Zero
- Is it available on other blockchains? No
- Metadata of the asset:
  + symbol: INW2
  + decimals: 12
  + contract address: [5EA7h2xCP9TkAwEQ8Km2b7aQChPKVCqcS2BJWqYavoXiEsfx](https://ascan.alephzero.org/mainnet/account/5EA7h2xCP9TkAwEQ8Km2b7aQChPKVCqcS2BJWqYavoXiEsfx)
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=1043-40&t=BT2EPMT87Se5Xgk6-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Can you provide a price key? n/a

**Comment by bluezdot** [comment]
Account has INW2: 5DCQ7mJMNsVWddfru82WpfmHyytyQQ8CFqEcmii4yRefRChi

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3094
