### ISSUE TITLE
[Kreivo] Add support for Kreivo Network

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#230]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: Kreivo Network is a Kusama parachain, it's a token-less parachain focused on real-world use cases.
- Basic information about your team: https://www.linkedin.com/company/virto-network/people/
- Whitepaper: https://virto.network/docs/whitepaper
- Social media links:
Twitter: https://x.com/VirtoNetwork
Website: https://virto.network/
- Github: https://github.com/virto-network/

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Kreivo
- Type of the blockchain: Substrate
- Blockchain providers: 
wss://kreivo.io/
wss://kreivo.kippu.rocks/
- Metadata of the blockchain:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkreivo.io%2F#/explorer
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6291-25&t=CacIRzYQfIZMGPwd-11

**Comment by bluezdot** [comment]
Account has KSM: EAMEHQZEhrH9bTuWHsTXdqPnY1WERiF37kjN385qxnTwHiT

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3094
