### ISSUE TITLE
[Polkadot Asset Hub] [HydraDX] Add support for BORK token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#233]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: BORK
- Symbol: BORK
- Origin blockchain of the asset: Polkadot Asset Hub
- Is it available on other blockchains? HydraDX
- Metadata of the asset:
Asset Hub ID: 690
  https://assethub-polkadot.subscan.io/assets/690
HydraDX ID: 1000148
  https://hydradx.subscan.io/custom_token?unique_id=asset_registry%2F906a8d0477a2a1a5e22d5c2b2093829ba52c40a8
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6370-794&t=lkyvyU5NSWxcqAoq-11
- Is your asset transferable: yes
- Is your asset listed on Coingecko? n/a

**Comment by bluezdot** [comment]
Account has BORK (Hydration): 7JpuBF7Zcv9TjWrMVEu6u83KAfkWHc2K8qa237PHXvYx333s
Account has BORK (PAH): 12ELtk1AQb3ftpN8RhUc7MHYT6jyq4MXFafkH3sKN46EJpiX

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3161
