### ISSUE TITLE
[Bifrost] Add vASTR token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#234]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: vASTR (Bifrost Voucher ASTR) 
- Origin blockchain of the asset: Bifrost
- Metadata of the asset: https://bifrost.subscan.io/custom_token?unique_id=asset_registry%2Ffd895658dd6eabfd9019f65834efc4c63b6904c8&tab=project
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6524-58&t=d6RhMxs0ThsHKYIN-11
- Is your asset transferable? Yes
- Can you provide a price key? https://www.coingecko.com/en/coins/bifrost-voucher-astr

**Comment by bluezdot** [comment]
account has vASTR: d6p1BH5zfArTwCmkZEukgXWJYEUe2skcFToFhV9XkU3FCdZ

**Comment by ThaoNguyen998** [comment]
Implement on issue https://github.com/Koniverse/SubWallet-Extension/issues/3185
