### ISSUE TITLE
[Analog] Add support for Analog Testnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#236]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: 
Analog is a suite of interoperability protocols built on the Substrate SDK. Analog aims to become a one-stop shop for multi-chain and cross-chain solutions, addressing native DApp development needs. 
- Basic information about your team: https://www.analog.one/team
- Whitepaper: https://www.analog.one/Analog-Timepaper.pdf
- Social media links ([twitter](https://twitter.com/OneAnalog), [telegram](http://t.me/analogtimer), [discord](https://discord.gg/analog), [website](https://www.analog.one/))
- Any other useful material so we can get to know you better: https://docs.analog.one/documentation

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Analog Testnet
- Type of the blockchain: Substrate, supports EVM
- Blockchain providers: wss://rpc.testnet.analog.one
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
https://metadata.analog.one/#/analog-testnet
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6561-60&t=4yz5cfglBSjbNQW4-4
- Block explorers: 
https://explorer.testnet.analog.one/#/
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.testnet.analog.one#/explorer

**Comment by bluezdot** [comment]
Account has TANLOG: an7Hw3uboJRhMsdCbgU7fNcJroLS9ee2tDeeg1u8GVyz1ss4e

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3214
