### ISSUE TITLE
[HydraDX] Add support for more tokens on HydraDX

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#237]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
| Name | Symbol | Metadata | Logo | Transferable | Coingecko |
|--------|--------|--------|--------|--------|--------|
| Phala | PHA | [Link](https://hydration.subscan.io/custom_token?unique_id=asset_registry%2F1ea51bf32497d1b3708522b430b288a129f65307) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=912-22&t=vuXgBmPXBFCGRJ1O-4) | Yes | [Link](https://www.coingecko.com/en/coins/phala-network) |
| KILT Protocol | KILT | [Link](https://hydration.subscan.io/custom_token?unique_id=asset_registry%2F2be4dc0e5a9f943bfb5a16beaa60c870d3a6678c) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=897-287&t=vuXgBmPXBFCGRJ1O-4) | Yes | [Link](https://www.coingecko.com/en/coins/kilt-protocol) |
| Zeitgeist | ZTG | [Link](https://hydration.subscan.io/custom_token?unique_id=asset_registry%2Fc4a2d99bc28d236098a095277b7eb0718d6be068) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=28-514&t=vuXgBmPXBFCGRJ1O-4) | Yes | [Link](https://www.coingecko.com/en/coins/zeitgeist) |
| Crust Network | CRU | [Link](https://hydration.subscan.io/custom_token?unique_id=asset_registry%2F1bc025202c93b9b72a2c672eba207ca423610c0a) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=28-412&t=vuXgBmPXBFCGRJ1O-4) | Yes | [Link](https://www.coingecko.com/en/coins/crust-network) |
| Darwinia Network | RING | [Link](https://hydration.subscan.io/custom_token?unique_id=asset_registry%2F8e10d9f1d511efdb3938b0d1ace5982c4e212da5) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=28-450&t=vuXgBmPXBFCGRJ1O-4) | Yes | [Link](https://www.coingecko.com/en/coins/darwinia-network) |
| Unique Network | UNQ | [Link](https://hydration.subscan.io/custom_token?unique_id=asset_registry%2F444d66d50aa517daed7fd36eb19a8857c2cd54e3) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=814-52&t=vuXgBmPXBFCGRJ1O-4) | Yes | [Link](https://www.coingecko.com/en/coins/unique-network) |

**Documents and references:**
Please attach all sources of the information you provided above
- https://app.hydration.net/liquidity/all-pools

**Comment by bluezdot** [comment]
- PHA: 7NFiPe5YtXATAtNWvWuNqmPeYu8YWdNdXF7jzZbr7dgkD1Tc
- KILT: 7LVyHM3kqQaeGXMpedzdaNn3dNYcXfVi76Ne4hWeVSjCDkcF
- ZTG: 7JP5mxd9Lwajp7cbPF4emGnSiLLz3o1JcTobQcqeVz7r2qeQ
- CRU: 7N2YhULaNEhm1N2QXkNMCCmGfXgarn974Jjdg6ZxEovd6SCv
- RING: 7NgQAyCDLxkKbozbchue7mpTA6Y2QTH7gATXHQSt7Ya9EC5J
- UNQ: 7NUJFMR9WkJKhnYXBVMT9zohSs8ijGtBZwjv8zkwtcPhNMQc

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3214
