### ISSUE TITLE
[Moonbeam] Add support for tokens listed on StellaSwap Pulsar

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#238]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**

| Name | Symbol | Contract | Metadata | Logo | Transferable | Coingecko |
|--------|--------|--------|--------|--------|--------|--------|
| Axelar Wrapped USDC | USDC.axl | 0xCa01a1D0993565291051daFF390892518ACfAD3A | [Link](https://moonbeam.subscan.io/erc20_token/0xCa01a1D0993565291051daFF390892518ACfAD3A) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6592-69&t=bs0XKKbWGF1bbbQn-11) | Yes | [Link](https://www.coingecko.com/en/coins/axelar-bridged-usdc) |
| Tether USD | USDT.wh | 0xc30E9cA94CF52f3Bf5692aaCF81353a27052c46f | [Link](https://moonbeam.subscan.io/erc20_token/0xc30E9cA94CF52f3Bf5692aaCF81353a27052c46f) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-490&t=vuXgBmPXBFCGRJ1O-4) | Yes | No |
| USDC (Wormhole) | USDC.wh | 0x931715fee2d06333043d11f658c8ce934ac61d0c | [Link](https://moonbeam.subscan.io/erc20_token/0x931715fee2d06333043d11f658c8ce934ac61d0c) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-489&t=vuXgBmPXBFCGRJ1O-4) | Yes | No |
| Wrapped BTC | WBTC.wh | 0xe57ebd2d67b462e9926e04a8e33f01cd0d64346d | [Link](https://moonbeam.subscan.io/erc20_token/0xe57ebd2d67b462e9926e04a8e33f01cd0d64346d) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-478&t=vuXgBmPXBFCGRJ1O-4) | Yes | No |
| Wrapped Ether | ETH.wh | 0xab3f0245b83feb11d15aaffefd7ad465a59817ed | [Link](https://moonbeam.subscan.io/erc20_token/0xab3f0245b83feb11d15aaffefd7ad465a59817ed) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=142-50&t=vuXgBmPXBFCGRJ1O-4) | Yes | No |
| Frax | FRAX | 0x322E86852e492a7Ee17f28a78c663da38FB33bfb | [Link](https://moonbeam.subscan.io/erc20_token/0x322e86852e492a7ee17f28a78c663da38fb33bfb) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=28-99&t=vuXgBmPXBFCGRJ1O-4) | Yes | [Link](https://www.coingecko.com/en/coins/frax) |

**Docs:**
https://docs.moonbeam.network/builders/interoperability/mrl/#tokens-available-through-wormhole
https://github.com/stellaswap/assets/tree/3c68698fa806f25ed9e5a68466ceb255e5f6cf0c/tokenlist
https://app.stellaswap.com/pulsar

**Comment by bluezdot** [comment]
- USDC.axl: 0x5f4ccBa86708D391f6719aEFEC4D5a4A9ab2eF70
- USDT.wh: 0x7369626cf2070000000000000000000000000000
- USDC.wh: 0x13FeFdD563A930F07B1aC8A2227Acc27c3C12946
- WBTC.wh: 0xaaa20c5a584a9fECdFEDD71E46DA7858B774A9ce
- ETH.wh: 0x7369626cf2070000000000000000000000000000
- FRAX: 0xd545Fd6080db07eDdcC1F57dC28a53D930837A8d

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3214
