### ISSUE TITLE
[Karura] Add support for Karura assets

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#239]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
Please add the following Karura assets:
- [x] USDCet
- [x] USDT

**Comment by bluezdot** [comment]
- Holder USDCet: No
- Holder USDT: pJGCBXbotxYx8SXTws8UJ112vwwAtztKsiiMWJJTiygwWsf

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/fqSB7x25Ass8sCQ
Validation passed
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/3a3c129e-d125-45ac-8739-0c95b1849d9b)
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/7ff5b58c-fb42-4669-94cc-6d82463e3001)

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3214
