### ISSUE TITLE
Add support for HashKey DID

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#24]
HashKey DID is a multichain decentralized identity data aggregator powered by smart contracts, NFTs, and privacy protection protocol. Please look into the docs below and see if SubWallet can integrate HashKey DID:
- Display the HashKey DIDs on SubWallet
- Support HashKey DID so that users can use the DIDs instead of wallet addresses for transferring assets

**Documents and references:**
- Website: https://www.hashkey.id/home
- IT doc: https://docs.hashkey.id/

Thank you!

**Comment by NamPhamc99** [comment]
Hashkey DID can be added through token import feature on SubWallet
