### ISSUE TITLE
Add support for Berachain testnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#240]
**If this is your first time integrating, the following information is required**
- Berachain is an EVM-identical L1 powered by Proof Of Liquidity
- Social media links ([telegram](https://t.me/BerachainPortal), [discord](https://discord.com/invite/berachain), [website](https://www.berachain.com/))
- Any other useful material so we can get to know you better: https://docs.berachain.com/
- Github: https://github.com/berachain

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Berachain bArtio
- Type of the blockchain: EVM
- Blockchain providers: https://bartio.rpc.berachain.com/
- Metadata of the blockchain: https://docs.berachain.com/learn/connect-to-berachain
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6661-141&t=oQCEQtDrJWDaKxfM-4
- Block explorers (if possible) https://bartio.beratrail.io/

**Comment by bluezdot** [comment]
holder: 0xB71b6cdF976b2A5Ae5d732b59246F608043fcD9E

**Comment by Sokol142196** [comment]
Version test: http://14.224.129.242:8900/s/EJxwyd8igttL46r
Validation passed in cases:
- Show network, token
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/3eebb2f8-b90d-4a8c-9b50-07f7dd50dffa)

- Show balance
  ![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/af765ffc-d24b-4c9b-829f-55a03304c8ef)
- Get address
  ![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/2f666bfc-d829-4686-9f1c-98b8a5d974d6)

- Transfer token (approve step)
  ![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/5eab009c-698f-4fdd-bd74-219f7346346a)
