### ISSUE TITLE
[OpenBit] Add support for LayerEdge Testnet

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#241]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: LayerEdge is the fastest, most inexpensive & developer-friendly bitcoin layer 2 with full EVM compatibility.
- Whitepaper: https://github.com/Layer-Edge/Whitepaper
- Social media links ([telegram](https://t.me/layeredge), [twitter](https://x.com/layeredge), [website](https://www.layeredge.io/))
- Any other useful material so we can get to know you better: https://docs.layeredge.io/
- Github: https://github.com/Layer-Edge

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: LayerEdge Testnet
- Type of the blockchain: EVM
- Blockchain providers: https://testnet-rpc.layeredge.io
- Metadata of the blockchain: https://docs.layeredge.io/technical-overview/networks
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2090-35&t=5kZg8H1QCi6mVGgu-0
- Block explorers: https://testnet-explorer.layeredge.io/

**Comment by bluezdot** [comment]
has BTC: 0x6eF9B3096521B988d04e48fe501D8285d8FA9f38

**Comment by bluezdot** [comment]
https://testnet-faucet.layeredge.io/
