### ISSUE TITLE
[OpenBit] Add support for Bitlayer Lucky Helmet NFT

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#243]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Bitlayer Lucky Helmet NFT
- Origin blockchain of the asset: Bitcoin
- Is it available on other blockchains? Yes - Bitlayer
- Metadata of the asset? Please check here: https://www.btrscan.com/token/0x260ac1a14a89fd24c72b84092629f14964556299?tab=Contract
- Logo of the token? Please check here: https://www.bitlayer.org/airdrop/lucky-helmet
- Is your asset transferable? Yes

**Comment by bluezdot** [comment]
https://www.btrscan.com/token/0x260ac1a14a89fd24c72b84092629f14964556299?tab=Holders
