### ISSUE TITLE
[OpenBit] Add support for BEVM OP Testnet

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#244]
**If this is your first time integrating, the following information is required**
- Any other useful material so we can get to know you better: https://documents.bevm.io/
- Github: https://github.com/btclayer2

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: BEVM OP Testnet
- Type of the blockchain: EVM
- Blockchain providers: https://sepolia-wbtc-testnet.bevm.io/
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...) - _Updating_
chainId: 11505
currency symbol: WBTC
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2-59&t=LnlB2luc3hNXPlCn-4
- Block explorers: https://scan-op-testnet.vercel.app/

**Comment by bluezdot** [comment]
WBTC holders: 0xcAF084133CBdBE27490d3afB0Da220a40C32E307
