### ISSUE TITLE
[OpenBit] [Merlin Chain] Add support for MERL token

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#245]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: MERL
- Origin blockchain of the asset: Merlin Chain
- Is it available on other blockchains? Yes
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
https://scan.merlinchain.io/token/0x5c46bFF4B38dc1EAE09C5BAc65872a1D8bc87378
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2326-25&t=NMFSvx2BWvfKA3KT-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Yes: https://www.coingecko.com/en/coins/merlin-chain

**Comment by bluezdot** [comment]
holders: https://scan.merlinchain.io/token/0x5c46bFF4B38dc1EAE09C5BAc65872a1D8bc87378
