### ISSUE TITLE
[OpenBit] Add support for tshx and Cncl token

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#248]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Token name: ToshiPad
- Token symbol: tshx
- Type: BRC-20
- Origin blockchain of the asset: Bitcoin
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
Please check here: https://www.oklink.com/btc/token/brc20/17456130?hmsr=unisat
and here: https://unisat.io/brc20/tshx
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2391-423&t=5jwaEXfKTenqcJK3-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Yes: https://www.coingecko.com/en/coins/toshipad
- Note: automatically enable

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Token name: The Ordinals Council
- Token symbol: Cncl
- Type: BRC-20
- Origin blockchain of the asset: Bitcoin
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
Please check here: https://ordiscan.com/inscription/968398
and here: https://ordinalswallet.com/inscription/a8827843471a3f3c88c285e1531eed639fb9eb3c348dc47811feb15a811e4a49i0
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2391-422&t=5jwaEXfKTenqcJK3-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Yes: https://www.coingecko.com/en/coins/cncl
- Note: automatically enable

**Comment by bluezdot** [comment]
tshx holder: bc1qxe526w4q4jsxjxyhd7z075nrvazqnnfxp34npn
Cncl holder: bc1qdem456xuzz602axylhtwh6jtwledzpw5qjm3l6
