### ISSUE TITLE
[OpenBit] Add support for more tokens on BounceBit

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#251]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**

| Name | Symbol | Metadata | Logo | Transferable | Coingecko |
|--------|--------|--------|--------|--------|--------|
| BounceBit BTC | BBTC | [Link](https://bbscan.io/token/0xF5e11df1ebCf78b6b6D26E04FF19cD786a1e81dC) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2407-23&t=8V0igfi7pQ6tKbyP-4) | Yes | [Link](https://www.coingecko.com/en/coins/bouncebit-btc) |
| BounceBit USD | BBUSD | [Link](https://bbscan.io/token/0x77776b40C3d75cb07ce54dEA4b2Fd1D07F865222) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2407-48&t=8V0igfi7pQ6tKbyP-4) | Yes | [Link](https://www.coingecko.com/en/coins/bouncebit-usd) |
| Liquid Staking BBTC | stBBTC | [Link](https://bbscan.io/token/0x7F150c293c97172C75983BD8ac084c187107eA19) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2407-49&t=8V0igfi7pQ6tKbyP-4) | Yes | No |
| Liquid Staking BB | stBB | [Link](https://bbscan.io/token/0x22aAC17E571D6651880d057e310703fF4C7c3483) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2407-50&t=8V0igfi7pQ6tKbyP-4) | Yes | No |

**Documents and references:**
- https://docs.bouncebit.io/token/bouncebit-tokenomics/liquid-staking-token-stbbtc-and-stbb
- https://docs.bouncebit.io/token/bouncebit-tokenomics/bitcoin-on-bouncebit-bbtc
- https://docs.bouncebit.io/token/bouncebit-tokenomics/stablecoins-on-bouncebit-bbusd

**Comment by bluezdot** [comment]
BBTC: https://bbscan.io/token/0xF5e11df1ebCf78b6b6D26E04FF19cD786a1e81dC?tab=Top+Holders
BBUSD: https://bbscan.io/token/0x77776b40C3d75cb07ce54dEA4b2Fd1D07F865222?tab=Top+Holders
stBBTC : https://bbscan.io/token/0x7F150c293c97172C75983BD8ac084c187107eA19?tab=Top+Holders
stBB: https://bbscan.io/token/0x22aAC17E571D6651880d057e310703fF4C7c3483?tab=Top+Holders
