### ISSUE TITLE
[OpenBit] Add support for more tokens on Bitlayer

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#252]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**

| Name | Symbol | Metadata | Logo | Transferable | Coingecko |
|--------|--------|--------|--------|--------|--------|
| Bitlayer-peg ORDI | ordi | [Link](https://www.btrscan.com/token/0xde9f57a5b8844ebf607eceffaa2505bb961701a4?tab=Transfers) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=62-114&t=BKfsHRyAXmMou2n0-4) | Yes | [Link](https://www.coingecko.com/en/coins/ordi) |
| Bitlayer-peg SATS | sats | [Link](https://www.btrscan.com/token/0x8dae8b60f16a10edfac1714394688e006ff369fa?tab=Holders) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=34-25&t=BKfsHRyAXmMou2n0-4) | Yes | [Link](https://www.coingecko.com/en/coins/sats-ordinals) |
| Bitlayer-peg RATS | rats | [Link](https://www.btrscan.com/token/0x0d922f10d86243ceff899f15571f51951e8b20f6?tab=Transfers) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2407-51&t=8V0igfi7pQ6tKbyP-4) | Yes | [Link](https://www.coingecko.com/en/coins/rats) |

**Documents and references:**
- https://www.btrscan.com/tokens

**Comment by bluezdot** [comment]
ordi holders: https://www.btrscan.com/token/0xde9f57a5b8844ebf607eceffaa2505bb961701a4?tab=Holders
