### ISSUE TITLE
[OpenBit] Add support for Rollux network

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#254]
**If this is your first time integrating, the following information is required**
- Rollux is the ultimate EVM superchain rooted in Bitcoin’s PoW for unparalleled security, scalability and affordability.
- Whitepaper: https://syscoin.org/research-whitepapers
- Social media links ([twitter](https://x.com/RolluxL2), [website](https://rollux.com/))
- Any other useful material so we can get to know you better: https://docs.rollux.com/
- Github: https://github.com/SYS-Labs/rollux
- Faucet: https://rollux.id/faucet?chainId=570

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Rollux
- Type of the blockchain: EVM
- Blockchain providers: https://rpc.rollux.com
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Please check here: https://docs.rollux.com/docs/help/start-using-rollux-mainnet/#rollux-mainnet-network-details
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2239-313&t=SfvHhXcc8eogPV5i-4 
- Block explorers: https://explorer.rollux.com

**Comment by bluezdot** [comment]
https://explorer.rollux.com/accounts
