### ISSUE TITLE
[Hydration] Add support for MYTH token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#255]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Mythos
- Symbol: MYTH
- Origin blockchain of the asset: Hydration
- Is it available on other blockchains? Yes - Mythos, Polkadot Asset Hub
- Metadata of the asset: https://hydration.subscan.io/custom_token?unique_id=asset_registry%2Fe4f2064efd114c35ce6939ef98789d88256e4ccf
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=3717-17&t=Ijq2QB7wtN4nEgUm-4
- Is your asset transferable? Yes
- Can you provide a price key? https://www.coingecko.com/en/coins/mythos

**Comment by bluezdot** [comment]
No holders
