### ISSUE TITLE
[Moonbeam] Add support for WIFD token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#256]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: xcWIFD (Dog Wif Dots)
- Origin blockchain of the asset: Moonbeam
- Is it available on other blockchains? Yes - Polkadot Asset Hub, Hydration
- Metadata of the asset: [0xfffffffF2e1D1ac9eA1686255bEfe995B31abc96](https://moonscan.io/token/0xfffffffF2e1D1ac9eA1686255bEfe995B31abc96)
https://moonbeam.subscan.io/assets/61295607754960722617854661686514597014
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6117-1684&t=Ijq2QB7wtN4nEgUm-4
- Is your asset transferable? Yes
- Can you provide a price key? n/a

**Documents and references:**
https://docs.moonbeam.network/builders/interoperability/xcm/xc20/overview/

**Comment by bluezdot** [comment]
WIFD holder: [0x45FbAf7de8f1D5B82189ba13aD47D103672c524D](https://moonbeam.subscan.io/account/0x45fbaf7de8f1d5b82189ba13ad47d103672c524d)
