### ISSUE TITLE
[OpenBit] Add support for Syscoin NEVM network

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#257]
**If this is your first time integrating, the following information is required**
- Whitepaper: https://syscoin.org/research-whitepapers
- Social media links ([website](https://syscoin.org/))
- Any other useful material so we can get to know you better: https://docs.syscoin.org/docs/intro/nutshell/
- Github: https://github.com/syscoin
- Faucet: https://faucet.syscoin.org/

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Syscoin NEVM
- Type of the blockchain: EVM
- Blockchain providers: https://rpc.syscoin.org
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Please check here: https://docs.syscoin.org/docs/guides/nevm/metamask/#mainnet
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2439-156&t=OXDzDSYV2GeL6WJ0-4
- Block explorers: https://explorer.syscoin.org/

**Comment by bluezdot** [comment]
https://explorer.syscoin.org/accounts
