### ISSUE TITLE
[OpenBit] Add support for more tokens on BOB

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#258]
**If you want to integrate a chain, you would need to provide**
| Name | Symbol | Metadata | Logo | Transferable | Coingecko |
|--------|--------|--------|--------|--------|--------|
| tBTC v2 | tBTC | [Link](https://explorer.gobob.xyz/address/0xBBa2eF945D523C4e2608C9E1214C2Cc64D4fc2e2) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=6661-93&t=ZYFrloMNwA9a1aMn-11) | Yes | [Link](https://www.coingecko.com/en/coins/tbtc) |
| Rocket Pool ETH | rETH | [Link](https://explorer.gobob.xyz/address/0xb5686c4f60904ec2bda6277d6fe1f7caa8d1b41a) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2453-794&t=jklrIVDTVDsx0Wk9-0) | Yes | [Link](https://www.coingecko.com/en/coins/rocket-pool-eth) |
| StakeStone Ether | STONE | [Link](https://explorer.gobob.xyz/address/0x96147a9ae9a42d7da551fd2322ca15b71032f342) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2453-1273&t=OXDzDSYV2GeL6WJ0-4) | Yes | [Link](https://www.coingecko.com/en/coins/stakestone-ether) |
| Dai Stablecoin | DAI | [Link](https://explorer.gobob.xyz/address/0x6c851f501a3f24e29a8e39a29591cddf09369080) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-480&t=6tJhzjtWFQwwbAq1-4) | Yes | [Link](https://www.coingecko.com/en/coins/dai) | 

Documents and references:
- https://docs.google.com/spreadsheets/d/12wTFxjjqAsmRKHNFeVHCOcZmesyJlrtCjUgIpZ229jc/edit?gid=0#gid=0

**Comment by bluezdot** [comment]
holders:
- tBTC: 0x8464d8e4C0489Bc776eD739B32c59431e4f8b77D
- rETH: 
- STONE:
- DAI: 0x12b26c563040A861f2911bC8c99cc23B24F9A8D4
