### ISSUE TITLE
Update chainlist

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-ChainList#259]
- [x] Update network name: Polimec Polkadot → Polimec
- [x] Add support for MYTH on Hydration: https://github.com/Koniverse/SubWallet-ChainList/issues/255
- [x] Add support for WIFD on Moonbeam: https://github.com/Koniverse/SubWallet-ChainList/issues/256

**Comment by bluezdot** [comment]
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/248
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/252
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/257
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/254
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/258
- [ ] https://github.com/openbitdev/OpenBit-Wallet/issues/181

**Comment by haiyenvu23** [comment]
Version test : 
- http://14.224.129.242:8900/s/eB4Y6g2WanK5CKW
- http://14.224.129.242:8900/s/z2NE6yRyJ3m88gm

Validation passed in case : 

- Install/Update version
-  Update network name: Polimec Polkadot → Polimec



![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/53bfa5a9-1efc-41c4-a4c5-da2cc614cd8d)


- Add support for MYTH on Hydration ( no holder)


![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/a441682c-e47a-4a03-808f-8acb937de65f)

-  Add support for WIFD on Moonbeam


![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/922a36a5-fce2-470e-8006-99681ab2b20c)
