### ISSUE TITLE
[OpenBit] Add support for B² Network Testnet

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#261]
**If this is your first time integrating, the following information is required**
- Any other useful material so we can get to know you better: https://docs.bsquared.network/
- Github: https://github.com/b2network
- Faucet: https://www.bsquared.network/faucet/

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: B² Network Testnet
- Type of the blockchain: ZK Rollup, EVM
- Blockchain providers: 
https://b2-testnet.alt.technology
https://rpc.ankr.com/b2_testnet
https://testnet-rpc.bsquared.network
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Please check here: https://docs.paddlefi.com/chains/bsquare#bitlayer-mainnet-1
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=8-40&t=0cDdBQaHQ9AaJAvH-4
- Block explorers: https://testnet-explorer.bsquared.network/
- Native token: BTC
- Name of native token: Bitcoin Testnet
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2239-197&t=0cDdBQaHQ9AaJAvH-4
- Is your asset transferable? Yes
- PriceID: N/A

**Comment by bluezdot** [comment]
holders: https://testnet-explorer.bsquared.network/top-accounts
