### ISSUE TITLE
[OpenBit] Add support for more tokens on B² Network

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#262]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
| Name | Symbol | Metadata | Logo | Transferable | Coingecko |
|--------|--------|--------|--------|--------|--------|
| Tether USD | USDT | [Link](https://explorer.bsquared.network/token/0x681202351a488040Fa4FdCc24188AfB582c9DD62) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-490&t=hp8F1qOKOjR0TSNy-4) | Yes | [Link](https://www.coingecko.com/en/coins/tether) |
| USD Coin | USDC | [Link](https://explorer.bsquared.network/token/0xE544e8a38aDD9B1ABF21922090445Ba93f74B9E5) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-489&t=hp8F1qOKOjR0TSNy-4) | Yes | [Link](https://www.coingecko.com/en/coins/usdc) |
| First Digital USD | FDUSD | [Link](https://explorer.bsquared.network/token/0xC2Fe4f673455Ef92299770a09CDB5E8756A525D5) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2502-175&t=7G3VMR42OXP85lH7-4) | Yes | [Link](https://www.coingecko.com/en/coins/first-digital-usd) |
| Matic Token | MATIC | [Link](https://explorer.bsquared.network/token/0xc3ee2Df14B1Bc526c24ED802f1873d49664a0d5c) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=302-518&t=hp8F1qOKOjR0TSNy-4) | Yes | [Link](https://www.coingecko.com/en/coins/polygon) |
| UniRouter BTC | uBTC | [Link](https://explorer.bsquared.network/token/0x796e4D53067FF374B89b2Ac101ce0c1f72ccaAc2) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2502-204&t=7G3VMR42OXP85lH7-4) | Yes | No | 
| STONE ETH | BSTONE | [Link](https://explorer.bsquared.network/token/0x7537C1F80c9E157ED7AFD93a494be3e1f04f1462) | [Link](https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2502-203&t=Q8wRoNpsXjjSEuf5-4) | Yes | No |
| Wrapped Ether | ETH | [Link](https://explorer.bsquared.network/token/0xD48d3A551757ac47655fCe25BDE1B0B6b1Cb2a5A) | [Link](https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=142-50&t=hp8F1qOKOjR0TSNy-4) | Yes | [Link](https://www.coingecko.com/en/coins/ethereum) |

**Documents and references:**
- https://explorer.bsquared.network/tokens

**Comment by bluezdot** [comment]
holders:
- USDT: https://explorer.bsquared.network/token/0x681202351a488040Fa4FdCc24188AfB582c9DD62
- USDC: https://explorer.bsquared.network/token/0xE544e8a38aDD9B1ABF21922090445Ba93f74B9E5
- FDUSD: https://explorer.bsquared.network/token/0xC2Fe4f673455Ef92299770a09CDB5E8756A525D5
- MATIC: https://explorer.bsquared.network/token/0xc3ee2Df14B1Bc526c24ED802f1873d49664a0d5c
- uBTC: https://explorer.bsquared.network/token/0x796e4D53067FF374B89b2Ac101ce0c1f72ccaAc2
- BSTONE: https://explorer.bsquared.network/token/0x7537C1F80c9E157ED7AFD93a494be3e1f04f1462
- ETH: https://explorer.bsquared.network/token/0xD48d3A551757ac47655fCe25BDE1B0B6b1Cb2a5A
