### ISSUE TITLE
[Aura] Add support for Aura Network

### ISSUE THREAD

**Issue by kienvc** [Koniverse/SubWallet-ChainList#264]
[Aura] Add support for Aura Network

**If this is your first time integrating, the following information is required**
- Social media links: https://aura.network
- An email: support@aura.network
- Github: https://github.com/aura-nw

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Aura Network
- Type of the blockchain (can be Substrate, EVM or both): EVM
- Blockchain providers: HTTP
- ChainID: 6322
- Symbol: AURA
- Decimal: 18
- JSON-RPC API: https://jsonrpc.aura.network
- Logo of the blockchain: https://github.com/aura-nw/mainnet-artifacts/blob/main/BrandKit/aura_6322-2/Symbol/Symbol-Color.svg
- Block explorers (if possible): https://aurascan.io

**Documents and references:**
- Docs: https://docs.aura.network/integrate/wallet/evm/integrate/

**Comment by Mabel-Nguyen** [comment]
- Price ID: https://www.coingecko.com/en/coins/aura-network

**Comment by bluezdot** [comment]
holders: 0x806d4a1cc6ee58129db1d5a5dec5bbd36b6b4655
