### ISSUE TITLE
[OpenBit] Add support for Rollux Testnet network

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#265]
**If this is your first time integrating, the following information is required**
- Any other useful material so we can get to know you better: https://docs.rollux.com/
- Github: https://github.com/SYS-Labs/rollux
- Faucet: https://rollux.id/faucet?chainId=57000

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Rollux Testnet
- Type of the blockchain: EVM
- Blockchain providers: https://rpc-tanenbaum.rollux.com
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Please check here: https://docs.rollux.com/docs/useful-tools/networks/#rollux-tanenbaum-testnet
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2239-313&t=SfvHhXcc8eogPV5i-4
- Block explorers: https://rollux.tanenbaum.io

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Test Syscoin
- Symbol: TSYS
- Origin blockchain of the asset: Rollux Testnet
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...): Native
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2439-44&t=OXDzDSYV2GeL6WJ0-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Can you provide a price key? (we use price service from Coingecko): N/A

**Comment by bluezdot** [comment]
holders: https://rollux.tanenbaum.io/accounts
