### ISSUE TITLE
[OpenBit] Add support for Syscoin NEVM Testnet network

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#266]
**If this is your first time integrating, the following information is required**
- Any other useful material so we can get to know you better: https://docs.syscoin.org/docs/intro/nutshell/
- Github: https://github.com/syscoin
- Faucet: https://rollux.id/faucet-nevm?chainId=5700

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Syscoin NEVM Testnet
- Type of the blockchain: EVM
- Blockchain providers: https://rpc.tanenbaum.io
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Please check here: https://docs.syscoin.org/docs/guides/nevm/metamask/#testnet
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2439-156&t=OXDzDSYV2GeL6WJ0-4
- Block explorers: https://tanenbaum.io

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Test Syscoin
- Symbol: TSYS
- Origin blockchain of the asset: Syscoin NEVM Testnet
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...): Native
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2439-44&t=OXDzDSYV2GeL6WJ0-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Can you provide a price key? (we use price service from Coingecko): N/A

**Comment by bluezdot** [comment]
Account has TSYS: 0x5E1BE25D4A2De0083012f1B5A8030a7023fFA5bc
