### ISSUE TITLE
[OpenBit] Add support for SatoshiVM Alpha Mainnet network

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#268]
**If this is your first time integrating, the following information is required**
- SatoshiVM is a decentralized Bitcoin ZK Rollup Layer 2 solution compatible with the EVM ecosystem, using native BTC as gas.
- Yellowpaper: https://github.com/SatoshiVM/yellowpaper
- Social media links ([twitter](https://twitter.com/SatoshiVM), [website](https://satoshivm.io/))
- Any other useful material so we can get to know you better: https://docs.satoshivm.io/
- Github: https://github.com/SatoshiVM

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: SatoshiVM Alpha Mainnet
- Type of the blockchain: EVM
- Blockchain providers: https://alpha-rpc-node-http.svmscan.io/
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Please check here: https://docs.satoshivm.io/user-guide/alpha-mainnet/network-information#satoshivm-alpha-mainnet
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=8-165&t=WNnAaID3bqh7KoeN-4
- Block explorers: https://svmscan.io/

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Bitcoin
- Symbol of the asset: BTC
- Origin blockchain of the asset: SatoshiVM Alpha Mainnet
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...): Native
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=34-43&t=WNnAaID3bqh7KoeN-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Yes - https://www.coingecko.com/en/coins/bitcoin

**Comment by bluezdot** [comment]
holders: https://svmscan.io/accounts
