### ISSUE TITLE
[OpenBit] Add support for SatoshiVM Testnet

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#269]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: SatoshiVM Testnet
- Type of the blockchain: EVM
- Blockchain providers: https://test-rpc-node-http.svmscan.io/
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Please check here: https://docs.satoshivm.io/user-guide/testnet/network-information#satoshivm-testnet
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=8-165&t=WNnAaID3bqh7KoeN-4
- Block explorers: https://testnet.svmscan.io/

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: BTC
- Origin blockchain of the asset: SatoshiVM Testnet
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
Please check here: https://docs.satoshivm.io/user-guide/testnet/network-information#satoshivm-testnet
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2239-197&t=8ugUM2hJZL6uBnDh-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Can you provide a price key? (we use price service from Coingecko): N/A

**Comment by bluezdot** [comment]
holders: https://testnet.svmscan.io/accounts
