### ISSUE TITLE
[OpenBit] Add support for SAVM token on SatoshiVM Alpha Mainnet 

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#270]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: SatoshiVM
- Symbol of the asset: SAVM
- Origin blockchain of the asset: SatoshiVM Alpha Mainnet
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
Please check here: https://svmscan.io/token/0x0E02765992f946397E6d2e65642eABb9cc674928
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2580-120&t=iOyEILtazIUl6RPI-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Yes - https://www.coingecko.com/en/coins/satoshivm

**Comment by bluezdot** [comment]
holders: https://svmscan.io/token/0x0E02765992f946397E6d2e65642eABb9cc674928?tab=holders
