### ISSUE TITLE
Add XCM support for MYTH token between Mythos <> PAH and Mythos <> Hydration

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#271]
Please help add XCM support for MYTH token:
- [x]  Polkadot Asset Hub <-> Mythos
- [x] Hydration <-> Mythos

https://mythos.subscan.io/xcm_channel

**Comment by bluezdot** [comment]
holder MYTH (Mythos): 0xeaf3223589ed19bcd171875ac1d0f99d31a5969c
holder MYTH (PAH): 13cKp88nRMkMK9jVQ84Xmt9w6bKEwnabVs6HJEK3PmZrxTCY
holder MYTH (Hydration): No

**Comment by bluezdot** [comment]
PAH -> Mythos: 0x4901041f0803010100a5340300010300cf50c83419eb10650ca7ac4741d9eef8451d390c03040002020907040300ba41ddf06b7ffd89d1267b5a93bfef2424eb2003001f4aa6e3420ebfc983d0157c0000000000
Hydradx -> Mythos: Ko có holders
Mythos -> PAH: 0x1101041f0803010100a10f03000101003e0779b1fc6b78bce8d79d6dfb3353d4686d20354455ce6cdcb169f08d018a5e0304000000001b4a4671b97a0c6f19be010000000000
Mythos -> Hydration: 0x1101041f0803010100c91f03000101003e0779b1fc6b78bce8d79d6dfb3353d4686d20354455ce6cdcb169f08d018a5e0304000000001b4a4671b97a0c6f19be010000000000
Hydradation -> Mythos: 0xd8048905030400010100a5340013000064a7b3b6e00d0000000003010200a53403003e0779b1fc6b78bce8d79d6dfb3353d4686d203500

**Comment by bluezdot** [comment]
- Hydration -> PAH (USDT): 0x1d01048905030400010300a10f043205011f0013000064a7b3b6e00d0000000003010200a10f01003e0779b1fc6b78bce8d79d6dfb3353d4686d20354455ce6cdcb169f08d018a5e00
- PAH -> Hydration (USDT):
0x1d01041f0803010100c91f03000101003e0779b1fc6b78bce8d79d6dfb3353d4686d20354455ce6cdcb169f08d018a5e0304000002043205011f0013000064a7b3b6e00d0000000000
- PAH -> Hydration (USDC): 0x1d01041f0803010100c91f03000101003e0779b1fc6b78bce8d79d6dfb3353d4686d20354455ce6cdcb169f08d018a5e0304000002043205e5140013000064a7b3b6e00d0000000000

**Comment by nampc1** [comment]
- [ ] MYTH: Hydration -> Mythos 0xd8048905030400010100a534001300008a5d784563010000000003010200a5340300dd718f9ecaf8f144a3140b79361b5d713d3a6b1900
- [ ] MYTH: Mythos -> Hydration 0x0901041f0803010100c91f0300010100a95c852dce76646efac76dd16bbe533af86333bd2a8725c4b356067da554537803040000000013000064a7b3b6e00d0000000000
- [ ] MYTH: Mythos -> AH 0x0901041f0803010100a10f03000101002c6dbbcb86ec6791ba672dcff246852de298bf67bc70fa5152e9684e04e3545b030400000000130000f444829163450000000000
- [ ] MYTH: AH -> Mythos

**Comment by bluezdot** [comment]
MYTH: PAH -> Mythos
0xe4041f0803010100a5340300010300dd718f9ecaf8f144a3140b79361b5d713d3a6b19030400010100a53400130000a2d732ecb7040000000000

**Comment by bluezdot** [comment]
https://github.com/Koniverse/SubWallet-Extension/issues/3453
