### ISSUE TITLE
[OpenBit] Add support for Bool Beta Testnet network

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#274]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Bool Beta Testnet
- Type of the blockchain: EVM
- Blockchain providers:
https://betatest-rpc-node-http.bool.network
wss://betatest-rpc-node-ws.bool.network
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Please check here: https://docs.bool.network/develop-guide/network-configuration#bool-beta-testnet
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2580-58&t=iOyEILtazIUl6RPI-4
- Block explorers (if possible): https://beta-testnet.boolscan.com/

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: tBOL
- Symbol of the asset: tBOL
- Origin blockchain of the asset: Bool Beta Testnet
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
Please check here: https://docs.bool.network/develop-guide/network-configuration#bool-beta-testnet
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2580-76&t=iOyEILtazIUl6RPI-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Can you provide a price key? (we use price service from Coingecko): N/A

**Comment by bluezdot** [comment]
holders: https://beta-testnet.boolscan.com/accounts
