### ISSUE TITLE
Update chainlist

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-ChainList#275]
- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/264
- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/271 (test display options on send fund screen. Do not need to test transfer XCM)
- [x] Update SQD token logo
- [x] Support Decoded collection from Unique https://uniquescan.io/unique/collections/665
- Support bifrost testnet https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbifrost-polkadot-rpc.devnet.liebi.com%2Fws#/accounts (Do not need test transfer, test this case on https://github.com/Koniverse/SubWallet-Extension/issues/3305)
- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/207

**Comment by nampc1** [comment]
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/273
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/274
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/265
- [ ] https://github.com/Koniverse/SubWallet-ChainList/issues/266
- [ ] Change symbol ò LayerEdge native token to LBTC

**Comment by haiyenvu23** [comment]
Version test ( SubWallet ) : http://14.224.129.242:8900/s/PRq3K7XZrRbdKg7

- [ ] Error when perform transfer NFT
Account test : 0x47886f3e49b7344722001db209f4beb55ebb2a8d
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/0d166839-a80b-40aa-8f67-f5604b0588f1)

**Comment by haiyenvu23** [comment]
[SubWallet]
Version test : 
- http://14.224.129.242:8900/s/HWX4XgyHyMnqGDx
- http://14.224.129.242:8900/s/7fa4exR4HznbFnk

Validation passed in case : 
- Install/Update version
- https://github.com/Koniverse/SubWallet-ChainList/issues/264
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/8295f3a5-97f8-4b23-9dff-11e8f1b2741d)

- https://github.com/Koniverse/SubWallet-ChainList/issues/271
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/760e82cc-dbb4-4647-9e7f-aacb6359052f)

-  Update SQD token logo
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/be4c440d-7097-4833-b764-34b4778c9fc9)

- Support Decoded collection from Unique https://uniquescan.io/unique/collections/665

> Perform send with Unique - EVM network
> Perform send with Unique network
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/a344dd3e-3268-4ee2-b1ba-4a82ec39afe0)

- https://github.com/Koniverse/SubWallet-ChainList/issues/207
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/2ae861c7-97dd-4c9a-a87d-f2abdb59d84e)

- Remove Bifrost testnet 
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/c708f9a4-98d1-4fcd-80c2-f289b325735f)

**Comment by haiyenvu23** [comment]
[OpenBit]
Version test : http://14.224.129.242:8900/s/E4A2kzxjbb4cBkd
Validation passed in case : 
- Install/Update version
- https://github.com/Koniverse/SubWallet-ChainList/issues/274

![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/1e82b633-00a1-4c73-bdc8-8ae6fa9dceeb)

- https://github.com/Koniverse/SubWallet-ChainList/issues/265
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/964b2362-fb1a-4fa1-a816-1b8b27f7b83f)

- https://github.com/Koniverse/SubWallet-ChainList/issues/266
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/bf3f07be-fc7e-4e45-b340-cfa10881f9b4)

 - Change symbol of LayerEdge native token to LBTC
 
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/155931563/077738e4-16ac-4d40-be8f-0f199d5004fe)
