### ISSUE TITLE
[OpenBit] Add support for Core Blockchain Mainnet network

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#276]
**If this is your first time integrating, the following information is required**
- Core Chain is the first Bitcoin-aligned EVM-compatible Layer-1 blockchain
- Social media links ([twitter](https://x.com/coredao_org), [website](https://coredao.org/))
- Any other useful material so we can get to know you better: https://docs.coredao.org/
- Github: https://github.com/coredao-org

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Core Blockchain Mainnet
- Type of the blockchain: EVM
- Blockchain providers: https://rpc.coredao.org/
- Metadata of the blockchain (chainId, paraId, addressPrefix, symbol,...)
Please check here: https://docs.coredao.org/docs/Dev-Guide/network-config#core-mainnet
- Logo of the blockchain: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2242-515&t=W9ATE2z7pLJotDq1-4
- Block explorers: https://scan.coredao.org/

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Core
- Symbol of the asset: CORE
- Origin blockchain of the asset: Core Blockchain Mainnet
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...): Native
- Logo of the token: https://www.figma.com/design/kx0dqXMzHmODOfWm9WMys0/02.OpenBit---Logo-Project?node-id=2242-515&t=W9ATE2z7pLJotDq1-4 
- Is your asset transferable? Yes
- Is your asset listed on any exchange? Yes - https://www.coingecko.com/en/coins/core

**Comment by bluezdot** [comment]
holders: https://scan.coredao.org/accounts
