### ISSUE TITLE
[Cere] Add support for Cere Network

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#277]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Cere Network
- Type of the blockchain: Substrate
- Blockchain providers (WS or HTTP)
wss://rpc.mainnet.cere.network/ws
- Metadata of the blockchain: https://cere.notion.site/Blockchain-Mainnet-f1424e5844ce4a8e9de9eb926f2a9261
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=28-281&t=nG7S73r87cyPdAox-4
- Block explorers: https://explorer.cere.network/

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
Please integrate CERE token on Ethereum as well:
- Name of the asset: CERE (Cere Network)
- Origin blockchain of the asset: Ethereum
- Is it available on other blockchains? No
- Metadata of the asset: [0x2dA719DB753dFA10a62E140f436E1d67F2ddB0d6](https://etherscan.io/token/0x2da719db753dfa10a62e140f436e1d67f2ddb0d6)
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=28-281&t=nG7S73r87cyPdAox-4
- Is your asset transferable? Yes
- Is your asset listed on any exchange? https://www.coingecko.com/en/coins/cere-network

**Comment by bluezdot** [comment]
holder on Cere substrate: 6Pqj4UwFRN4mmu25PH8RqWaMT4jNd6ytFNgaJ4KtVTfgByez

**Comment by bluezdot** [comment]
holders CERE on Ethereum: https://etherscan.io/token/0x2da719db753dfa10a62e140f436e1d67f2ddb0d6#balances
