### ISSUE TITLE
Update chain-list

### ISSUE THREAD

**Issue by nampc1** [Koniverse/SubWallet-ChainList#279]
- [x] Remove Avail Goldberg testnet
- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/278
- [x] https://github.com/Koniverse/SubWallet-ChainList/issues/277
- [x] https://github.com/Koniverse/SubWallet-Extension/issues/3335

**Comment by haiyenvu23** [comment]
[OpenBit]
Version test : http://14.224.129.242:8900/s/E5dzEze45zWpEmE
Validation passed in case : 
- Install/Update version 
- https://github.com/Koniverse/SubWallet-ChainList/issues/276
![image](https://github.com/user-attachments/assets/c61f8476-8293-4cee-8856-bae22d040b6e)

- https://github.com/Koniverse/SubWallet-ChainList/issues/268
![image](https://github.com/user-attachments/assets/76f14955-e7f2-498b-8bbc-e3b44c55d4fb)

- https://github.com/Koniverse/SubWallet-ChainList/issues/269
![image](https://github.com/user-attachments/assets/78161eb5-6fda-49c1-b45d-662d648423c5)

- https://github.com/Koniverse/SubWallet-ChainList/issues/270
![image](https://github.com/user-attachments/assets/eee2afdd-ca48-4f44-bab5-4b3427054ba7)

**Comment by haiyenvu23** [comment]
[SubWallet]
Version test : 
- http://14.224.129.242:8900/s/8wjnaHLZzPig86Q
- (Firefox): http://14.224.129.242:8900/s/tTFKYjNGxiGqMYQ
Validation passed in case : 
- Install/Update version
- Remove Avail Goldberg testnet


![Image](https://github.com/user-attachments/assets/415f7217-b887-4d21-992f-6029949d5aad)


 - https://github.com/Koniverse/SubWallet-ChainList/issues/278
 

![Image](https://github.com/user-attachments/assets/d59b0b2d-5035-467c-b8bb-e41adb9ba245)


 - https://github.com/Koniverse/SubWallet-ChainList/issues/277
 

![Image](https://github.com/user-attachments/assets/bd14f192-8e5e-49c2-814b-523ab5eb0f97)



![Image](https://github.com/user-attachments/assets/2826c351-a21f-43eb-9b12-bafb4131d381)


 - https://github.com/Koniverse/SubWallet-Extension/issues/3335
 

![Image](https://github.com/user-attachments/assets/79007e7a-d9ea-407f-b9aa-e58446162e6a)

**Comment by kolkadot** [comment]
@haiyenvu23 thx a lot for the speedy update here! You guys are quick, good job!

How long will it take to be reflected in the SubWallet? I noticed that it doesn't show up yet:
<img width="383" alt="image" src="https://github.com/user-attachments/assets/6e80c284-7e3a-4995-bbb7-dddcd9609987">

Do users have to update the wallet somehow or will this be rolled out automatically later?

**Comment by haiyenvu23** [comment]
@kolkadot Currently the version of SubWallet on the store is 1.2.15. This part/this token will be supported in version 1.2.16, it should be ready in the next 1-2 days, please wait
