### ISSUE TITLE
Update for tDOT and tKSM

### ISSUE THREAD

**Issue by vincnetlee** [Koniverse/SubWallet-ChainList#28]
1. Need to update the icon for tDOT on Acala network
2. Need to rename the "taiKSM" on Karura network to "tKSM"
![tDOT](https://github.com/Koniverse/SubWallet-ChainList/assets/57982612/2809e01b-3fa7-4698-a771-ef8bb27a1389)

**Comment by NamPhamc99** [comment]
@vincnetlee please update more details following this guideline https://github.com/Koniverse/SubWallet-ChainList/wiki/Start-contributing-to-the-project

**Comment by vincnetlee** [comment]
@NamPhamc99 sorry, what specific detail needs?

**Comment by NamPhamc99** [comment]
> @NamPhamc99 sorry, what specific detail needs?

Are you from Acala team? can you link a source that shows these information? We need a reference in order to verify that information being submitted is correct

**Comment by vincnetlee** [comment]
I am from Taiga. Please check this links
https://dot.taigaprotocol.io/assets
https://app.taigaprotocol.io/assets
