### ISSUE TITLE
add support for Circle EURC on Pendulum

### ISSUE THREAD

**Issue by annatekl** [Koniverse/SubWallet-ChainList#280]
This request is for adding support for Circle EURC asset registered on Pendulum

| Asset name  | Origin blockchain |Price Key |Is it available on other blockchains? |Is your asset transferable? |
| ------------- | ------------- |------------- |------------- |------------- |
| Circle EURC | Stellar |https://stellar.expert/explorer/public/asset/EURC-GDHU6WRG4IEQXM5NZ4BMPKOXHW76MZM4Y2IEMFDVXBSDP6SJY4ITNPP2-1 |Yes |Yes |

#### Asset metadata
```
Asset id: {
          Stellar: {
          AlphaNum4: {
            code: EURC
            issuer: 0xcf4f5a26e2090bb3adcf02c7a9d73dbfe6659cc690461475b86437fa49c71136
          }
decimals: 12
name: Circle EURC
symbol: EURC.s
```

**Comment by Mabel-Nguyen** [comment]
- Logo: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7023-304&t=tOqXbytrgr0FHFbS-4

**Comment by bluezdot** [comment]
cant find account has balance

**Comment by annatekl** [comment]
6crgzCSvCAimAEkCxctFZginxL6uUfYKijHBVsAK5WGhcJY1

**Comment by bluezdot** [comment]
@annatekl Do you have explorer or anything else to check these non-native token holders? I just ask for later integration

**Comment by annatekl** [comment]
Pendulum is on subscan, but this asset was recently added to our network so I don't think we have many holders of Circle EURC
