### ISSUE TITLE
[Ethereum] [Polygon] Add support for ROUTE token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#283]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: ROUTE (Router Protocol)
- Origin blockchain of the asset: Ethereum, Polygon
- Is it available on other blockchains? Yes
- Metadata of the asset:
Ethereum: https://etherscan.io/token/0x60F67E1015b3f069DD4358a78c38f83fE3a667A9
Polygon: https://polygonscan.com/token/0x93890f346C5D02C3863a06657bc72555dC72c527
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7067-34&t=a813fVlFnTkwq7QO-4
- Is your asset transferable? Yes
- Coingecko: https://www.coingecko.com/en/coins/router-protocol-2

**Documents and references:**
Please attach all sources of the information you provided above
https://routerprotocol.medium.com/comprehensive-route-migration-bridging-and-staking-guide-d0b9f1dd2ef3

**Comment by bluezdot** [comment]
holders on polygon: https://polygonscan.com/token/0x93890f346C5D02C3863a06657bc72555dC72c527#balances
holders on ethereum: https://etherscan.io/token/0x60F67E1015b3f069DD4358a78c38f83fE3a667A9#balances
