### ISSUE TITLE
add support for Pendulum assets (ASTR, vDOT, BNC)

### ISSUE THREAD

**Issue by annatekl** [Koniverse/SubWallet-ChainList#284]
This request is for adding support for assets registered on Pendulum: ASTR, vDOT, BNC

| Asset name  | Origin blockchain |Price Key |Is it available on other blockchains? |Is your asset transferable? |
| ------------- | ------------- |------------- |------------- |------------- |
| ASTR | Astar |https://www.coingecko.com/en/coins/astar |Yes|Yes |
| BNC | Bifrost |https://www.coingecko.com/en/coins/bifrost-native-coin |Yes|Yes |
| vDOT | Bifrost |https://www.coingecko.com/en/coins/voucher-dot |Yes|Yes |

#### Asset metadata:

ASTR:
```
{
        XCM: 9
      }
    ]
    {
      decimals: 18
      name: Astar
      symbol: ASTR
      existentialDeposit: 0
      location: {
        V3: {
          parents: 1
          interior: {
            X1: {
              Parachain: 2,006
            }
          }
```

BNC:
```
{
        XCM: 11
      }
    ]
    {
      decimals: 12
      name: Bifrost Native Token
      symbol: BNC
      existentialDeposit: 10,000,000,000
      location: {
        V3: {
          parents: 1
          interior: {
            X2: [
              {
                Parachain: 2,030
              }
```

vDOT:
```
{
        XCM: 10
      }
    ]
    {
      decimals: 10
      name: Voucher DOT
      symbol: vDOT
      existentialDeposit: 1,000,000
      location: {
        V3: {
          parents: 1
          interior: {
            X2: [
              {
                Parachain: 2,030
              }
```

![vDOT](https://github.com/user-attachments/assets/2cac34d2-ac0b-4c58-b074-616140b0a6f4)
![BNC](https://github.com/user-attachments/assets/6e1b5afb-14c6-4a3d-89f8-37a5c02e199f)
![ASTR_Color](https://github.com/user-attachments/assets/8b095abc-f791-4404-ac0e-e9dc721b1f1c)

**Comment by Mabel-Nguyen** [comment]
Logos:
- ASTR: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=897-311&t=TPy2ZLHZ7qMzQHQ2-4
- BNC: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=760-42&t=TPy2ZLHZ7qMzQHQ2-4
- vDOT: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=957-65&t=TPy2ZLHZ7qMzQHQ2-4

**Comment by bluezdot** [comment]
holder: 6crgzCSvCAimAEkCxctFZginxL6uUfYKijHBVsAK5WGhcJY1
