### ISSUE TITLE
[Aleph Zero] Add support for Aleph Zero EVM (mainnet)

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#285]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Aleph Zero - EVM
- Type of the blockchain: EVM
- Blockchain providers: 
https://rpc.alephzero.raas.gelato.cloud
wss://ws.alephzero.raas.gelato.cloud
- Metadata of the blockchain: https://raas.gelato.network/rollups/details/public/aleph-zero-evm
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=27-2035&t=nG7S73r87cyPdAox-4
- Block explorers (if possible) https://aleph-zero-evm.blockscout.com

**Comment by bluezdot** [comment]
@Mabel-Nguyen, will add block explorer later when it's available for use.

**Comment by bluezdot** [comment]
cant find holders (no explorer)

**Comment by Mabel-Nguyen** [comment]
> @Mabel-Nguyen, will add block explorer later when it's available for use.

Block explorer is up, please check: https://aleph-zero-evm.blockscout.com
