### ISSUE TITLE
[Exosama] Add support for Exosama network

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#287]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Exosama
- Type of the blockchain: EVM
- Blockchain providers: https://chainlist.org/chain/2109
- Metadata of the blockchain: https://docs.moonsama.com/docs/exosama-network/About
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7135-94&t=LPH8bew6aNrbH5Oe-4
- Block explorers: https://explorer.exosama.com/

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: SAMA (SAMA)
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7135-94&t=LPH8bew6aNrbH5Oe-4
- Is your asset transferable? Yes
- Coingecko: https://www.coingecko.com/en/coins/moonsama

**Comment by bluezdot** [comment]
SAMA holder:
[0xD0672Aa0e6F391D2c3ea95797FB07E8d49bbB17f](https://explorer.exosama.com/address/0xD0672Aa0e6F391D2c3ea95797FB07E8d49bbB17f)
