### ISSUE TITLE
[Blast] Add support for Blast Mainnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#288]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: Blast is an EVM chain with native yield for ETH and stablecoins
- Document: https://docs.blast.io/about-blast
- Social media links ([discord](https://discord.com/invite/blastdevelopers), [website](https://blast.io/en),...)
- Github: https://github.com/blast-io

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Blast Mainnet
- Type of the blockchain: EVM
- Blockchain providers: https://rpc.blast.io
- Metadata of the blockchain: https://docs.blast.io/building/network-information
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7207-91&t=0IsuhPRdmoCAwlpL-4
- Block explorer: https://blastscan.io/

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: BLAST (Blast)
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7207-91&t=0IsuhPRdmoCAwlpL-4
- Coingecko: https://www.coingecko.com/en/coins/blast
- Doc: https://docs.blast.io/tokenomics

**Comment by bluezdot** [comment]
https://blastscan.io/token/0xb1a5700fa2358173fe465e6ea4ff52e36e88e2ad#balances
