### ISSUE TITLE
[DENTnet] Add in-app staking support for DENTX

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#289]
- Staking doc: https://docs.dentnet.io/dentnet-documentation/overview/core-concepts/proof-of-stake/staking
- Dashboard: https://main.dentnet.io/dashboard/#/overview

**Comment by bluezdot** [comment]
5GngHp6nfGB7J4SLgXZENBrVLA6Dop4bVVjUUHdCp6dFMLGt
