### ISSUE TITLE
[5ireChain] Add 5ireChain mainnet support 

### ISSUE THREAD

**Issue by dung5ire** [Koniverse/SubWallet-ChainList#291]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain : `5ireChain Mainnet` 
- Type of the blockchain : `Substrate with EVM-compatible` 
- Blockchain providers: `https://rpc.5ire.network/`
- Metadata of the blockchain:
   + Chain ID: `995` 
- Logo of the blockchain: https://drive.google.com/drive/folders/1ZErYYOJItj7Ul25NbJ_csOnBLnlMP8dy
- Block explorers (if possible): `https://5irescan.io/`

**Please take a look at https://github.com/Koniverse/SubWallet-Chain/blob/master/CONTRIBUTING.md**

**Comment by Mabel-Nguyen** [comment]
- Logo: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7259-42&t=bvtrt2diAFcgLRtG-4
- Coingecko: https://www.coingecko.com/en/coins/5ire

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3478
