### ISSUE TITLE
[Mantle Network] Add support for Mantle Network and tokens

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#311]
**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Mantle Network
- Type of the blockchain: EVM
- Blockchain providers: https://rpc.mantle.xyz/
- Metadata of the blockchain: https://docs-v2.mantle.xyz/devs/dev-guides/quick#network-details
- Logo of the blockchain: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7565-57&t=GCw2p3z4BHVJZ1BN-4
- Block explorers: https://mantlescan.xyz/

**Native token MNT**
- Name of the asset: MNT (Mantle)
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7565-57&t=GCw2p3z4BHVJZ1BN-4
- Is your asset transferable? Yes
- Coingecko: https://www.coingecko.com/en/coins/mantle

**Integrate token mETH**
- Name of the asset: mETH (Mantle Staked Ether)
- Origin blockchain of the asset: Mantle Network
- Is it available on other blockchains? Yes
- Metadata of the asset: https://explorer.mantle.xyz/token/0xcDA86A272531e8640cD7F1a92c01839911B90bb0
https://mantlescan.xyz/token/0xcda86a272531e8640cd7f1a92c01839911b90bb0
- Logo of the token: https://www.figma.com/design/z9s6aLTLoUdjMwoXLyWcPz/01.SubWallet-Project-Logo?node-id=7571-235&t=D0OBOoEt5N2CAoWU-4
- Is your asset transferable? Yes
- Coingecko: https://www.coingecko.com/en/coins/mantle-staked-ether

**Comment by haiyenvu23** [comment]
Need update logic estimated fee -> Improve later
