### ISSUE TITLE
[Bifrost] Add referral code for Bifrost Liquid Staking (vDOT, vMANTA)

### ISSUE THREAD

**Issue by meandhwh** [Koniverse/SubWallet-ChainList#332]
Please help add the referral code/link below for Bifrost Liquid Staking (vDOT, vMANTA) inside SubWallet:

- Referral link: https://app.bifrost.io/vstaking/?channel=7
- Dashboard to track: https://rsp.bifrost.io/channel?channelId=7

**Context:**
- Adopt new API for Bifrost Liquid Staking (vDOT, vMANTA) on SubWallet. It includes a channel_id function within vtoken_minting that SubWallet had integrated. This function enables SubWallet to earn additional commission on every DOT or MANTA staking through the wallet.

**Documents and references:**
- https://docs.bifrost.io/partners/reward-share-program-rsp/join-the-program
- https://docs.google.com/spreadsheets/d/1YeR9XNSATWr3EtVtvGigCHnry3bxNj0O_cFZshGMybg/edit?gid=0#gid=0

**Comment by haiyenvu23** [comment]
Version test : http://14.224.129.242:8900/s/ySRHMR2gHoDLT47
Validation passed in case
- Install/Update vesion
- Check when perform stake with vDOT on normal account

   ![Image](https://github.com/user-attachments/assets/412b7564-dee3-4fee-bc31-949585cc9be8)

   Link explorer : https://bifrost.subscan.io/extrinsic/0x70191be506fb73bf6a30879fc10d3881c6d26c5cb92d6d4c700f9760570ff8e2

- Check when stake on Ledger account

   ![Image](https://github.com/user-attachments/assets/1da96b0a-929e-4419-89e4-6f1e5d668dd5)

- Re-check when stake some token types
