### ISSUE TITLE
[Bifrost] Update prefix for Bifrost

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-ChainList#361]
** Please name the issue/PR after this format**
Update prefix for Bifrost

- [x] Bifrost Polkadot
- [x] Bifrost Kusama
- [x] Bifrost Testnet

**Comment by Sokol142196** [comment]
Patch version: Patch data 0.2.97-beta.5

**Check with Bifrost Polkadot** 
- Get the address (Normal account, Ledger account)
  
![image](https://github.com/user-attachments/assets/28117f07-ac3a-4975-90c2-780e00a7d261)

- Transfer on wallet
  - Local token: https://bifrost.subscan.io/extrinsic/0xa1b3721cbcd2349c3e8eaabcb33330b75765953648cb2c6718bfa19421dbd4f9
    ![image](https://github.com/user-attachments/assets/59de78e9-556f-4686-b8a9-423c14d34e3a)
  - Native token: https://bifrost.subscan.io/extrinsic/0x49491bdc8da67158a7bbfac273039f9ac8192927b8c526d7b53b476fdc399a09
  ![image](https://github.com/user-attachments/assets/24800f79-69ec-4e16-9907-48867814548f)
  - XCM transfer
    ![image](https://github.com/user-attachments/assets/31905726-9d9d-4a9a-a165-b5fa12863473)

- Transfer on dApp: Check with Polkadot js app
  ![image](https://github.com/user-attachments/assets/23eb8593-14c2-4ad3-a890-a7c643ea6136)

 
- Check get history:
![image](https://github.com/user-attachments/assets/f7ddcc0c-3188-49ce-965b-cbc1b5bab277)

- Earning (check to Approve step)
  ![image](https://github.com/user-attachments/assets/4823d94e-4b8f-41ad-a9b3-b96312c1f16f)


**Check with Bifrost Kusama**
- Get address
  ![image](https://github.com/user-attachments/assets/ec4f346f-585e-4423-8b8e-50e88572679e)

- Transfer on Wallet: https://bifrost-kusama.subscan.io/extrinsic/0x5f5b83ecb213dff606e699fe175b56ad06c0f2ffb5c17eafa8fce244930e2564
  ![image](https://github.com/user-attachments/assets/7446332d-febd-4a41-bac2-b0b643c01e96)

- Transfer with dApp
  ![image](https://github.com/user-attachments/assets/4c2f1148-92ce-4e68-9849-408c086a5c52)
  ![image](https://github.com/user-attachments/assets/dbdcdd05-0b55-4ecc-a17e-f8687ea9446f)


- Check history
  ![image](https://github.com/user-attachments/assets/cbde10e8-84e9-42e9-aa98-eff1d26e2b1e)

- Show NFT
- Earning (Check to Approve step)

-------
Need to re-check:
- [ ] Buy token with BNC (Bifrost Kusama)
  ![image](https://github.com/user-attachments/assets/d5845886-d99a-401d-8de2-e9baff2fb649)

**Comment by boundless-forest** [comment]
I noticed the Bifrost prefix changed from 6 to 0 in this commit https://github.com/Koniverse/SubWallet-ChainList/commit/09305adfd9f09863dc993ca00c6a9806030b183c#diff-c7cac0909011d8b580a3882b420241945561f52e1be0f3b51c5982fb3e48aa0cL1180. Could you clarify why it was updated? The SS58 registry https://github.com/paritytech/ss58-registry/blob/main/ss58-registry.json#L68 still shows an address prefix of 6 for Bifrost, which is confusing. We are building an XCM transfer app https://github.com/ringecosystem/paralink that depends on this JSON file and have observed the prefix change. Please explain the rationale for it.

![image](https://github.com/user-attachments/assets/cb23d056-0107-4841-b2ce-820373a9838d)

**Comment by bluezdot** [comment]
@boundless-forest, I do not know about the reason why they change the prefix. I think the data in ss58-registry file is not yet updated. Did you try to create an issue on the repo `https://github.com/paritytech/ss58-registry`?

**Comment by boundless-forest** [comment]
I know the reason behind this, thanks for your reply.
