### ISSUE TITLE
[Bifrost network] Add vsTokens and vTokens

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-ChainList#4]
**Describe the solution you'd like**

1. Integrate vsTokens (ORML Token) on Bifrost into SubWallet

Bifrost SALP mechanism: 
- [https://hackmd.io/7gf6E-btT52WKnpIwCKM9w](https://hackmd.io/7gf6E-btT52WKnpIwCKM9w)
- [https://hackmd.io/Y51sSMBvQiWTXKBB-TljQQ](https://hackmd.io/Y51sSMBvQiWTXKBB-TljQQ)

SALP apis:
- [https://hackmd.io/erri6l3ESP690XEDC_zTnw](https://hackmd.io/erri6l3ESP690XEDC_zTnw)

2. Integrate vTokens on Bifrost into SubWallet
- vToken is staking derivative
- Bifrost 2023 roadmap: https://bifrost-finance.notion.site/7df6abf2acb54b398df75230e157c7da?v=02ecfe941c5242c3b5f8c77654512b80

=> List added tokens:

- [x] vDOT
- [x] vGLMR
- [x] vKSM
- [x] vMOVR
- [x] vBNC
- [x] vsDOT
- [x] vsKSM

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./master-pr-1520-build-1.0.8-2023-06-12T02-42-40UTC.zip
Validation passed for cases:
- Show token
- Show balance
- Transfer token (approve step)
