### ISSUE TITLE
Add USDT, USDC on EVM chains

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-ChainList#41]
Add USDT, USDC for EVM chains:
- [x] Polygon
- [x] Arbitrum
- [x] Optimism
- [x] Tomochain

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1438-build-1.0.5-2023-05-24T13-13-58UTC.zip

@S2kael Please verify USDT and USDC
- Actual: Show multiple USDT, USDC token on token list 

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/ece2fa95-97fa-412a-bb53-c3ee9b036c9c)

**Comment by S2kael** [comment]
Verified: USDC - moonriver
Not verified: USDT, USDC - shidenEvm
