### ISSUE TITLE
[AlephZero] [InkWhale] [INW] Comprehensive platform to launch new tokens, crypto projects and raise liquidity on Aleph Zero

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-ChainList#43]
** Please name the issue/PR after this format**
[AlephZero] [InkWhale] [INW] Comprehensive platform to launch new tokens, crypto projects and raise liquidity on Aleph Zero

**If this is your first time integrating, the following information is required**
- Comprehensive platform to launch new tokens, crypto projects and raise liquidity on Aleph Zero
- ArtZero Team
- [Whitepaper (if you have one)](https://inkwhale.net/)
- [Social media links (telegram, discord, website, linkedin,...)](https://twitter.com/inkwhale_net)

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- INW
- AlephZero
- Smart Contract: 5H4aCwLKUpVpct6XGJzDGPPXFockNKQU2JUVNgUw6BXEPzST
- Logo of the token: 
![inkwhale](https://github.com/Koniverse/SubWallet-ChainList/assets/2582652/5ea7a622-cf67-4262-afeb-1523a2625975)

- Is your asset transferable?

**Comment by mitchdoan** [comment]
Please name the issue/PR after this format
[INW - Aleph Zero] Add logos for tokens created on Inkwhale.net on Subwalllet

If this is your first time integrating, the following information is required
- NFT staking, yield farming, launchpad, orderbook on Aleph Zero blockchain
- Same team with Artzero.io team including: Brian Nguyen (CEO), Phoebe Hoang (CMO), Mitch Doan (BD), Shinie Nguyen (marketing), Dev: Nam Hoang, Cuong Tran, Long nguyen, Thien Nguyen, Tung Vu, Huy Pham
- Whitepaper: https://docs.inkwhale.net
- Social media links:
website: https://inkwhale.net
twitter: https//twitter.com/@inkwhale_net
telegram: https://t.me/inkwhale

- Any other useful material so we can get to know you better: https://docs.inkwhale.net, we are on mainnet at https://a0.inkwhale.net
- contact@artzero.io
- Github
- Any grant information you can provide (W3F Grants, Substrate Builders Program,...)- Yes we received milestones grant from W3F

@RyanDinh8 @Mabel-Nguyen

If you want to integrate an asset (fungible token/ NFT), you would need to provide
- Name of the asset
- Origin blockchain of the asset
- Is it available on other blockchains?
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
- Logo of the token
- Is your asset transferable?



Documents and references:
Please attach all sources of the information you provided above

Please take a look at https://github.com/Koniverse/SubWallet-Chain/blob/master/CONTRIBUTING.md

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/1541
