### ISSUE TITLE
[Astar] [AI Serpenators Collection] Add Support For NFT Collection

### ISSUE THREAD

**Issue by katehasw** [Koniverse/SubWallet-ChainList#44]
This issue is from Astar x ArtZero x SubWallet Campaign. 
Please add support for AI Serpenators NFT Collection:

**Contract Address**: WCX5y1WsgPBxQqtn75jXNtHey9w4EZSEKCdjg2jX3gcA97D
**Creator**: WriGREuj8U1U8nVmv57H1Gr1DyZk6eimf3wx4NJndyFqRno
**Ink NFT
Astar Network**

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1438-build-1.0.6-0-2023-05-25T12-16-59UTC.zip

@NamPhamc99 Re-check show image of this NFT.
- Check with address: 5C8VumbGx4KoJCdAf5ptMz48wCFzv4dJbGkJ6fJap2wVS76t


![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/eba940fb-63a5-4a8f-acaa-1718390c4aac)

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1438-build-1.0.6-0-2023-05-26T09-12-47UTC.zip

Validation passed.
