### ISSUE TITLE
[Ethereum] [Bitcoin.com] [VERSE] Add support for VERSE token

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#48]
**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: 
Since 2015, Bitcoin.com has been a global leader in introducing newcomers to crypto. We make it easy for anyone to buy, spend, trade, invest, earn, and stay up-to-date on cryptocurrency and the future of finance. VERSE, which launched in December 2022, is Bitcoin.com’s rewards and utility token. VERSE is fueling the growth and expansion of Bitcoin.com’s ecosystem, which includes over 39 million self-custody wallets created in its multi-chain DeFi-ready mobile app, the Bitcoin.com Wallet. 
- Whitepaper: https://www.getverse.com/verse-whitepaper.pdf
- Social media links (telegram, discord, website, LinkedIn,...)
Website: https://www.bitcoin.com/
Twitter: https://twitter.com/bitcoincom
Telegram: https://t.me/www_Bitcoin_com
Discord: https://discord.com/invite/bitcoincom
- Github: https://github.com/bitcoin-portal

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: 
VERSE
- Origin blockchain of the asset: 
Ethereum
- Is it available on other blockchains?
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
0x249cA82617eC3DfB2589c4c17ab7EC9765350a18
- Logo of the token
https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=840-31&t=AjMJ5BGh9vVyZRhM-0
- Is your asset transferable?
Yes

**Documents and references:**
https://etherscan.io/token/0x249cA82617eC3DfB2589c4c17ab7EC9765350a18

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./master-pr-1520-build-1.0.8-2023-06-12T02-42-40UTC.zip

Validation passed for cases:
- Show token
- Show balance
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/220749bc-d66d-4475-a58f-f1c0e2740d20)

- Transfer
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/0f1dea74-0fb9-4e05-a41f-af002f197827)
