### ISSUE TITLE
Re-check RPC for some chains

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/SubWallet-ChainList#52]
Describe the task
Recheck and update RPC for some chains
- Link file: File re-check: https://konistudio-my.sharepoint.com/:x:/g/personal/nhungphung_koni_studio/EWZ4LuNzaZ5NiPhULm82rnsBVn0eIyjQ06F2KmU_Y6FnsA?e=oMNslS

**Comment by Sokol142196** [comment]
File re-check: https://konistudio-my.sharepoint.com/:x:/g/personal/nhungphung_koni_studio/EWZ4LuNzaZ5NiPhULm82rnsBVn0eIyjQ06F2KmU_Y6FnsA?e=oMNslS

**Comment by NamPhamc99** [comment]
- [ ] Write a script to detect RPC error
- [ ] Understand how to connect to a substrate/evm chain using WS or HTTP provider
- [ ] Learn how to find provider for chains

**Comment by Sokol142196** [comment]
Continue to update in https://github.com/Koniverse/SubWallet-ChainList/issues/146
