### ISSUE TITLE
[Astar Network] [Neurolauncher] [NRL] A WASM NFT Collection on the Astar Network

### ISSUE THREAD

**Issue by ahmetzturk** [Koniverse/SubWallet-ChainList#56]
![neurolauncher-icon-nobg](https://github.com/Koniverse/SubWallet-ChainList/assets/51791622/0c447a03-197e-4897-acda-a426869935e1)
- Name of the asset - Neurolauncher
- Origin blockchain of the asset - Astar Network
- Is it available on other blockchains? - No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...) - NRL, bYLgJmSkWd4S4pTEacF2sNBWFeM4bNerS27FgNVcC9SqRE4
- Logo of the token
- Is your asset transferable? - Yes

<img width="80" alt="neurolauncher-icon" src="https://github.com/Koniverse/SubWallet-ChainList/assets/51791622/6577e67f-b8cd-4853-ac1b-acb1c39a3210">

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./master-pr-1520-build-1.0.8-2023-06-12T02-42-40UTC.zip

Validation passed with address aERWBFHUXSs5w5LNCo4F5EwUDVtfFjBLEDDADCWd3XZJxXc
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/b742e441-a59d-4b1b-a7a3-e012c828a615)
