### ISSUE TITLE
[Kintsugi] [Interlay] Add support for LP tokens on Kintsugi

### ISSUE THREAD

**Issue by Mabel-Nguyen** [Koniverse/SubWallet-ChainList#59]
Hi team, please add support for Kintsugi's LP token pairs:
- LP kBTC-USDT
- LP KSM-kBTC
- LP KSM-KINT

See docs at https://docs.interlay.io/#/developers/tokens?id=token-types for more details. All tokens (including the LP tokens) are stored in the **tokens** pallet.
- Link logo: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=1123-146&mode=design&t=BHLaTlOdMtAyWDkC-0

**Comment by NamPhamc99** [comment]
please provide these information:
- An address which has balance of those LPs
- Decimal of LP tokens
- Logo of LP tokens
- Price of LP tokens (optional)

**Comment by Mabel-Nguyen** [comment]
Hi @NamPhamc99 please see the info provided by Interlay team below. Let me know if you need anything else!

- Address with tokens on Kintsugi: 
a3dkY3yWweLMkUjbSSNC2NawWegH3NZkWpYjsnBr2srQsp9LZ
- Decimal:
LP tokens decimals are 18
- Logo:
All token icons can be found in this link:
https://github.com/interlay/interbtc-ui-icons

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/1590
