### ISSUE TITLE
[Astar] [Paras NFT] [USAGII] Add USAGII NFT collection from Paras

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-ChainList#62]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: USAGII
- Origin blockchain of the asset: Astar
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
Contract address:  WvyVtR9Ktvxa9fRRFJPXvEgYTU5K5Lf491xzFhMQL3haDN6
Type: PSP34
- Logo of the token
- Is your asset transferable? Yes

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./master-pr-1520-build-1.0.8-2023-06-12T09-05-50UTC.zip
_- Check with address: YDTpoNMbS9fCUqXMnwDcFb8NmfMqBxx2ugwSAwYHeGH9ZGY_

Validation passed for cases:
- Show NFT
- Send NFT (approve step)
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/38a463f0-5b76-412c-abb6-4be6b7faa4bc)
