### ISSUE TITLE
[Calamari] Update provider

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-ChainList#68]
Describe the task
Update provider: wss://calamari.systems

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1527-build-1.0.9-0-2023-06-13T04-50-21UTC.zip

Validation passed!
- Connected successfully

![Image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/cb98b46a-d2d2-4f86-8217-0cce71cc0548)
