### ISSUE TITLE
Support zk assets

### ISSUE THREAD

**Issue by hieudd** [Koniverse/SubWallet-ChainList#7]
**Support zk assets**

- [x] https://manta.network/: https://github.com/Koniverse/SubWallet-Extension/issues/1525
- https://zksync.io/: https://github.com/Koniverse/SubWallet-Extension/issues/1619
- https://polygon.technology/polygon-zkevm: https://github.com/Koniverse/SubWallet-Extension/issues/1621
- Linea zkEVM](https://linea.build/): https://github.com/Koniverse/SubWallet-Extension/issues/1622

**Comment by RyanDinh8** [comment]
Manta zkAddress & zkAsset docs:

- https://docs.manta.network/docs/guides/MantaSigner
- https://github.com/Manta-Network/sdk => you should switch to signer_extension branch
- https://www.npmjs.com/package/manta-extension-sdk

**Comment by hieudd** [comment]
> Manta zkAddress & zkAsset docs:
> 
> * https://docs.manta.network/docs/guides/MantaSigner
> * https://github.com/Manta-Network/sdk => you should switch to signer_extension branch
> * https://www.npmjs.com/package/manta-extension-sdk

@NamPhamc99 pls check this documentation

**Comment by hieudd** [comment]
@NamPhamc99 pls check this wallet: https://chrome.google.com/webstore/detail/leo-wallet/nebnhfamliijlghikdgcigoebonmoibm/related
