### ISSUE TITLE
[Avail] Add support for Avail testnet (Kate)

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-ChainList#70]
** Please name the issue/PR after this format**
Add support for Kate testnet on Avail - a Substrate-based blockchain
- [x] Viewing balance
- Transfering & Staking: improve later (https://github.com/Koniverse/SubWallet-ChainList/issues/75)

**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team: Avail is a Substrate-based blockchain founded by Anurag - one of Polygon co-founders (https://www.availproject.org/)
- Social media links (telegram, discord, website, linkedin,...)
- Twitter: https://twitter.com/AvailProject
- Discord: https://discord.com/invite/y6fHnxZQX8
- Github: https://github.com/availproject

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain: Avail Kate Testnet
- Type of the blockchain (can be Substrate, EVM or both): Substrate
- Explorer: https://kate.avail.tools/
- RPC Endpoint: https://kate.avail.tools/v1
- WS Endpoint: wss://kate.avail.tools/ws
- Chain Specification: [chainspec.raw.json](https://availproject.github.io/assets/files/chainspec.raw-1905ee8ba4620c9cd6f1f378a84346eb.json)
- Chain Info: [chaininfo.txt](https://kate.avail.tools/chaininfo.txt)
- Docs: https://availproject.github.io/join-the-network/networks
- API changes: https://github.com/availproject/avail/blob/da91630d5c472ff738058698dd8e5b7cf4694ea2/tests/js_api/src/api.ts#L8-L134
- Logo: 
![photo_2023-06-14_10-42-52](https://github.com/Koniverse/SubWallet-ChainList/assets/102496727/4945bff2-6e54-49da-a8a6-bcb713417f86)

**Comment by S2kael** [comment]
Have some problem with sign transaction.
It will be resolved in https://github.com/Koniverse/SubWallet-Extension/issues/1222

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/1541
