### ISSUE TITLE
Add support for $CP token on Moonbeam

### ISSUE THREAD

**Issue by RyanDinh8** [Koniverse/SubWallet-ChainList#76]
** Please name the issue/PR after this format**
[Blockchain] [Your project name (optional)] [Asset symbol (optional)] A short description of your issue

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- CP
- Moonbeam
- Smart contract: 0x6021D2C27B6FBd6e7608D1F39B41398CAee2F824
- Logo of the token: 
![photo_2023-05-30_20-02-53 (2)](https://github.com/Koniverse/SubWallet-ChainList/assets/102496727/d41a7726-c249-44b7-9057-f813233e329b)
![photo_2023-05-30_20-02-53](https://github.com/Koniverse/SubWallet-ChainList/assets/102496727/df752bcc-da46-4df0-946e-1b9d88179a8a)

- Is your asset transferable? => Yes

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/1556
