### ISSUE TITLE
[Bifrost] Add support for Vtoken

### ISSUE THREAD

**Issue by katehasw** [Koniverse/SubWallet-ChainList#78]
Please add support for vETH & vFIL if possible.

Bifrost SALP mechanism:

- https://hackmd.io/7gf6E-btT52WKnpIwCKM9w
- https://hackmd.io/Y51sSMBvQiWTXKBB-TljQQ
SALP apis:

- https://hackmd.io/erri6l3ESP690XEDC_zTnw
- Integrate vTokens on Bifrost into SubWallet

vToken is staking derivative

Bifrost 2023 roadmap: https://bifrost-finance.notion.site/7df6abf2acb54b398df75230e157c7da?v=02ecfe941c5242c3b5f8c77654512b80

More docs on vETH and vFIL:
- vETH: https://wiki.bifrost.finance/staking-liquidity-protocol-slp/veth
- vFIL: https://wiki.bifrost.finance/staking-liquidity-protocol-slp/vfil

**Comment by Mabel-Nguyen** [comment]
Token Logos:
- vFIL: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/SubWallet-Project-Logo?type=design&node-id=957-67&mode=design&t=PjmzMG2dUThdrwiO-0
- vETH: https://github.com/bifrost-finance/design-assets/tree/master/token_logo/veth

**Comment by Sokol142196** [comment]
Resolved in https://github.com/Koniverse/SubWallet-Extension/issues/1576
