### ISSUE TITLE
[Pendulum] [USDT DOT] Add support for USDT, DOT on Pendulum

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-ChainList#82]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
DOT
- Origin: Polkadot
- Is it available on other blockchains? yes
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...): XCM currency id: 0
- Logo of the token
- Is your asset transferable? yes

USDT
- Origin: Statemint
- Is it available on other blockchains? yes
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...): XCM currency id: 1
- Logo of the token
- Is your asset transferable? yes

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1631-build-1.1.1-2023-07-12T05-14-36UTC.zip

Validation passed for cases:
- Show balance
- Send token (Approve step)
