### ISSUE TITLE
[Aleph Zero] [ZapFi] [$ZPF] Token Metadata Addition on SubWallet

### ISSUE THREAD

**Issue by DaddyDillZero** [Koniverse/SubWallet-ChainList#83]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: ZPF Token
- Origin blockchain of the asset: Aleph Zero
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...):
   Contract Address: 5ESKJbkpVa1ppUCmrkCmaZDHqm9SHihws9Uqqsoi4VrDCDLE
   Symbol: ZPF
   Decimal: 12
- Logo of the token
![zpf-logo-icon](https://github.com/Koniverse/SubWallet-ChainList/assets/117751434/4d875b45-a232-43be-88cc-13102173f228)

- Is your asset transferable? Yes

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1720-build-1.1.5-2023-08-01T08-03-40UTC.zip
- Added the pre-defined logo for this token
![image](https://github.com/Koniverse/SubWallet-ChainList/assets/130966515/07ca409b-f0ef-43ad-bb3c-34fbdc4a0512)
