### ISSUE TITLE
[Aleph Zero] [Panorama swap] [PANX] Add PANX token

### ISSUE THREAD

**Issue by NamPhamc99** [Koniverse/SubWallet-ChainList#95]
**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset: Panorama swap token
- Origin blockchain of the asset: Aleph Zero
- Is it available on other blockchains? No
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
  Contract address: 5GSGAcvqpF5SuH2MhJ1YUdbLAbssCjeqCn2miMUCWUjnr5DQ
- Is your asset transferable? Yes

**Comment by Sokol142196** [comment]
Version test: https://file.cdmteck.com/s/4oimk9zDJ8R5Aai/download?path=%2F&files=./upgrade-ui-pr-1720-build-1.1.5-2023-08-01T08-03-40UTC.zip

Validation passed for cases:
- Show token
- Send token
