### ISSUE TITLE
[Deeper-chain] [Deeper Network] [DPR] Add support for Deeper-Chain

### ISSUE THREAD

**Issue by AmadeusGB** [Koniverse/SubWallet-ChainList#97]
** Please name the issue/PR after this format**
[Deeper-chain] [Deeper Network] [DPR] Add support for Deeper-Chain

**If this is your first time integrating, the following information is required**
- A short introduction about your project/ your team
Deeper Network is committed to building a truly decentralized Internet and security gateway. It aims to bring a better Internet experience for every family and become the gateway for users to Web 3.0 applications. Deeper’s vision is to combine network security, network sharing, and blockchain technology to create a safer, freer, and faster decentralized network.
- Whitepaper: https://cdn.shopifycdn.net/s/files/1/0256/1038/7504/files/deeper_network_whitepaper_4.2_en.pdf?v=1684808898
- Social media links (telegram, discord, website, linkedin,...)
- Twitter:  https://twitter.com/deeper_network
- Telegram: https://t.me/DeeperNetwork
- Discord:  https://discord.gg/SM9q2zzYT7
- Github: https://github.com/deeper-chain
- Website：https://www.deeper.network/
- W3F Grants: https://github.com/w3f/Grants-Program/blob/master/applications/deeper_network.md

**If you want to integrate a chain, you would need to provide**
- Name of the blockchain：Deeper-Chain
- Type of the blockchain (can be Substrate, EVM or both): Substrate
- Apps-chain addressPrefix: 42
- Apps-chain RPC：https://mainnet-deeper-chain.deeper.network/rpc
- Apps-chain WSS: wss://mainnet-full.deeper.network
- Apps-chain Explorer: https://apps.deeper.network/#/explorer
- Block Explorer: https://www.deeperscan.io/deeper
- EVM RPC: https://mainnet-deeper-chain.deeper.network/rpc
- EVM ChainId: 518
- EVM Explorer: https://evm.deeper.network/
- Token Symbol: DPR
- Docs：https://deeper-network-inc.gitbook.io/deeper-connect-knowledge-base/
- Logo: https://drive.google.com/file/d/1ShjCWMA7syfyBX2oUbQQtP5KS0PIf5qF/view?usp=drive_link

**If you want to integrate an asset (fungible token/ NFT), you would need to provide**
- Name of the asset
- Origin blockchain of the asset
- Is it available on other blockchains? 
- Metadata of the asset (symbol, decimals, smart contract address, on-chain metadata like assetId,...)
- Logo of the token
- Is your asset transferable?

Note:
- If you want to add a smart contract asset, then you would need to provide proof that your project is active and there are users/holders
- Make sure your logo follow this styling: https://www.figma.com/file/PxPvXw5woBernBu3BtwxkX/Polkadot-Project-Logo?node-id=13-2096&t=dwcwfywiIfHXXiBv-0

**Comment by NamPhamc99** [comment]
Thanks for providing information in detail, we'll take this request into our plan

**Comment by Sokol142196** [comment]
Deeper chain available at SubWallet V1.1.8
